/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graderecords;
import DBConn.koneksi;
import DBDao.StudentDAO;
import DBDao.TeacherDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author J8138
 */
public class GradeRecordsGUI extends javax.swing.JFrame {

    ResultSet rs;
    Connection conn;
    Statement st;
    PreparedStatement prep;
    TeacherDAO teach;
    StudentDAO stud;
    String[][] dataStudent;
    
    public GradeRecordsGUI() {
        initComponents();        
        panelAfterLogin.show(false);
        panelLogin.show(true);
        conn = new koneksi().setConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAwal = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        panelIcon = new javax.swing.JPanel();
        panelFormLogin = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblIconNama = new javax.swing.JLabel();
        lblIconPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        panelAfterLogin = new javax.swing.JPanel();
        panelIconAfterLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtlog_name = new javax.swing.JLabel();
        txtlog_class = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        panelInsert = new javax.swing.JPanel();
        lblFormInsert = new javax.swing.JLabel();
        lblNamaI = new javax.swing.JLabel();
        lblKelasI = new javax.swing.JLabel();
        lblMatI = new javax.swing.JLabel();
        lblFisikaI = new javax.swing.JLabel();
        lblBindoI = new javax.swing.JLabel();
        lblBinggrisI = new javax.swing.JLabel();
        lblBiologiI = new javax.swing.JLabel();
        btnInsertForm = new javax.swing.JButton();
        textNama = new javax.swing.JTextField();
        textKelas = new javax.swing.JTextField();
        textMat = new javax.swing.JTextField();
        textFis = new javax.swing.JTextField();
        textBI = new javax.swing.JTextField();
        textBing = new javax.swing.JTextField();
        textBio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textNIM = new javax.swing.JTextField();
        panelButton = new javax.swing.JPanel();
        buttonInsert = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        btn_add_student = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        panelUpdate = new javax.swing.JPanel();
        lblTITLEFORM = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMat = new javax.swing.JLabel();
        lblFisika = new javax.swing.JLabel();
        lblBindo = new javax.swing.JLabel();
        lblBinggris = new javax.swing.JLabel();
        lblBiologi = new javax.swing.JLabel();
        btnUpdateForm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textNIMu = new javax.swing.JTextField();
        textNamau = new javax.swing.JTextField();
        textKelasu = new javax.swing.JTextField();
        textMatu = new javax.swing.JTextField();
        textFisu = new javax.swing.JTextField();
        textBIu = new javax.swing.JTextField();
        textBingu = new javax.swing.JTextField();
        textBiou = new javax.swing.JTextField();
        panelDelete = new javax.swing.JPanel();
        lblFormDelete = new javax.swing.JLabel();
        lblNamaD = new javax.swing.JLabel();
        lblKelasD = new javax.swing.JLabel();
        lblMatD = new javax.swing.JLabel();
        lblFisikaD = new javax.swing.JLabel();
        lblBindoD = new javax.swing.JLabel();
        lblBinggrisD = new javax.swing.JLabel();
        lblBiologiD = new javax.swing.JLabel();
        btnDeleteForm = new javax.swing.JButton();
        panelUpdateSos = new javax.swing.JPanel();
        lblTITLESOS = new javax.swing.JLabel();
        lblNamaSos = new javax.swing.JLabel();
        lblKelasSos = new javax.swing.JLabel();
        lblMatSos = new javax.swing.JLabel();
        lblIPS = new javax.swing.JLabel();
        lblBindoSos = new javax.swing.JLabel();
        lblBinggrisSos = new javax.swing.JLabel();
        btnUpdateSos = new javax.swing.JButton();
        lblNIMsos = new javax.swing.JLabel();
        textNIMuSos = new javax.swing.JTextField();
        textNamauSos = new javax.swing.JTextField();
        textKelasuSos = new javax.swing.JTextField();
        textMatuSos = new javax.swing.JTextField();
        textIPS = new javax.swing.JTextField();
        textBIuSos = new javax.swing.JTextField();
        textBinguSos = new javax.swing.JTextField();
        panelDeleteSos = new javax.swing.JPanel();
        lblFormDeleteSos = new javax.swing.JLabel();
        lblNamaDSos = new javax.swing.JLabel();
        lblKelasDSos = new javax.swing.JLabel();
        lblMatDSos = new javax.swing.JLabel();
        lblIPSDSos = new javax.swing.JLabel();
        lblBindoDSos = new javax.swing.JLabel();
        lblBinggrisD1 = new javax.swing.JLabel();
        btnDeleteFormSos = new javax.swing.JButton();
        panelInsertSos = new javax.swing.JPanel();
        lblFormInsertSos = new javax.swing.JLabel();
        lblNamaI1 = new javax.swing.JLabel();
        lblKelasI1 = new javax.swing.JLabel();
        lblMatI1 = new javax.swing.JLabel();
        lblUNIPS = new javax.swing.JLabel();
        lblBindoISos = new javax.swing.JLabel();
        lblBinggrisI1 = new javax.swing.JLabel();
        btnInsertFormSos = new javax.swing.JButton();
        textNamaSos = new javax.swing.JTextField();
        textKelasSos = new javax.swing.JTextField();
        textMatSos = new javax.swing.JTextField();
        textIPSinsert = new javax.swing.JTextField();
        textBISos = new javax.swing.JTextField();
        textBingSos = new javax.swing.JTextField();
        lblNIMSos = new javax.swing.JLabel();
        textNIMSos = new javax.swing.JTextField();
        panelButtonSos = new javax.swing.JPanel();
        buttonInsertSos = new javax.swing.JButton();
        btnShowSos = new javax.swing.JButton();
        buttonUpdateSos = new javax.swing.JButton();
        buttonDeleteSos = new javax.swing.JButton();
        btn_add_student1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAwal.setBackground(new java.awt.Color(255, 255, 255));
        PanelAwal.setLayout(null);

        panelLogin.setBackground(new java.awt.Color(242, 238, 229));
        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 232, 206), 10));
        panelLogin.setLayout(null);

        panelIcon.setBackground(new java.awt.Color(194, 232, 206));

        javax.swing.GroupLayout panelIconLayout = new javax.swing.GroupLayout(panelIcon);
        panelIcon.setLayout(panelIconLayout);
        panelIconLayout.setHorizontalGroup(
            panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        panelIconLayout.setVerticalGroup(
            panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        panelLogin.add(panelIcon);
        panelIcon.setBounds(20, 20, 840, 160);

        panelFormLogin.setBackground(new java.awt.Color(194, 232, 206));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitle.setText("LOGIN FORM");

        lblIconNama.setBackground(new java.awt.Color(255, 255, 255));
        lblIconNama.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblIconNama.setText("USERNAME :");

        lblIconPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblIconPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblIconPassword.setText("PASSWORD :");

        txtName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLoginLayout = new javax.swing.GroupLayout(panelFormLogin);
        panelFormLogin.setLayout(panelFormLoginLayout);
        panelFormLoginLayout.setHorizontalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLoginLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIconPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIconNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFormLoginLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(lblTitle))
                    .addGroup(panelFormLoginLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        panelFormLoginLayout.setVerticalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIconNama)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIconPassword)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addContainerGap())
        );

        panelLogin.add(panelFormLogin);
        panelFormLogin.setBounds(20, 200, 840, 230);

        PanelAwal.add(panelLogin);
        panelLogin.setBounds(0, 0, 880, 460);

        panelAfterLogin.setBackground(new java.awt.Color(194, 232, 206));
        panelAfterLogin.setMinimumSize(new java.awt.Dimension(680, 450));
        panelAfterLogin.setLayout(null);

        panelIconAfterLogin.setBackground(new java.awt.Color(242, 238, 229));
        panelIconAfterLogin.setPreferredSize(new java.awt.Dimension(427, 141));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Logged in as : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Class :");

        txtlog_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlog_name.setText("- - -");

        txtlog_class.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlog_class.setText("- - -");

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIconAfterLoginLayout = new javax.swing.GroupLayout(panelIconAfterLogin);
        panelIconAfterLogin.setLayout(panelIconAfterLoginLayout);
        panelIconAfterLoginLayout.setHorizontalGroup(
            panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconAfterLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIconAfterLoginLayout.createSequentialGroup()
                        .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlog_class)
                            .addComponent(txtlog_name)))
                    .addComponent(btn_logout))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        panelIconAfterLoginLayout.setVerticalGroup(
            panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconAfterLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtlog_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlog_class))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_logout)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelAfterLogin.add(panelIconAfterLogin);
        panelIconAfterLogin.setBounds(12, 12, 425, 141);

        panelInsert.setBackground(new java.awt.Color(242, 238, 229));

        lblFormInsert.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormInsert.setText("INSERT FORM");

        lblNamaI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaI.setText("NAMA SISWA/SISWI :");

        lblKelasI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasI.setText("KELAS  :");

        lblMatI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatI.setText("NILAI UN MATEMATIKA :");

        lblFisikaI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblFisikaI.setText("NILAI UN FISIKA :");

        lblBindoI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoI.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisI.setText("NILAI UN BAHASA INGGRIS :");

        lblBiologiI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBiologiI.setText("NILAI UN BIOLOGI :");

        btnInsertForm.setText("INSERT");
        btnInsertForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertFormActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setText("NIM :");

        javax.swing.GroupLayout panelInsertLayout = new javax.swing.GroupLayout(panelInsert);
        panelInsert.setLayout(panelInsertLayout);
        panelInsertLayout.setHorizontalGroup(
            panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertLayout.createSequentialGroup()
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInsertLayout.createSequentialGroup()
                        .addComponent(lblKelasI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMat)
                            .addComponent(textKelas)
                            .addComponent(textFis)
                            .addComponent(textBI)
                            .addComponent(textBing)
                            .addComponent(textBio)))
                    .addGroup(panelInsertLayout.createSequentialGroup()
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaI)
                            .addComponent(jLabel1))
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNama)
                            .addComponent(textNIM)))
                    .addGroup(panelInsertLayout.createSequentialGroup()
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInsertLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblFormInsert))
                            .addComponent(lblFisikaI)
                            .addComponent(lblBiologiI, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMatI)
                            .addComponent(lblBinggrisI)
                            .addComponent(lblBindoI, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelInsertLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnInsertForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInsertLayout.setVerticalGroup(
            panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaI)
                    .addComponent(textNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelasI)
                    .addComponent(textKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatI)
                    .addComponent(textMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFisikaI)
                    .addComponent(textFis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindoI)
                    .addComponent(textBI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggrisI)
                    .addComponent(textBing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiologiI)
                    .addComponent(textBio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInsertForm)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelInsert);
        panelInsert.setBounds(455, 12, 423, 431);

        panelButton.setBackground(new java.awt.Color(242, 238, 229));

        buttonInsert.setText("INSERT");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        btnShow.setText("SHOW");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        buttonUpdate.setText("UPDATE");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("DELETE");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        btn_add_student.setText("Add new Student");
        btn_add_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_studentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonLayout.createSequentialGroup()
                        .addComponent(buttonInsert)
                        .addGap(36, 36, 36)
                        .addComponent(btnShow)
                        .addGap(38, 38, 38)
                        .addComponent(buttonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(buttonDelete))
                    .addGroup(panelButtonLayout.createSequentialGroup()
                        .addComponent(btn_add_student, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsert)
                    .addComponent(btnShow)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_add_student)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelAfterLogin.add(panelButton);
        panelButton.setBounds(12, 167, 425, 100);

        panelTable.setBackground(new java.awt.Color(242, 238, 229));

        scrollPanel.setBackground(new java.awt.Color(242, 238, 229));

        tableSiswa.setBackground(new java.awt.Color(242, 238, 229));
        tableSiswa.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama Siswa/Siswi", "Kelas", "Status"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        scrollPanel.setViewportView(tableSiswa);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );

        panelAfterLogin.add(panelTable);
        panelTable.setBounds(12, 273, 425, 185);

        panelUpdate.setBackground(new java.awt.Color(242, 238, 229));

        lblTITLEFORM.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblTITLEFORM.setText("UPDATE FORM");

        lblNama.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNama.setText("NAMA SISWA/SISWI :");

        lblKelas.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelas.setText("KELAS  :");

        lblMat.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMat.setText("NILAI UN MATEMATIKA :");

        lblFisika.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblFisika.setText("NILAI UN FISIKA :");

        lblBindo.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindo.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggris.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggris.setText("NILAI UN BAHASA INGGRIS :");

        lblBiologi.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBiologi.setText("NILAI UN BIOLOGI :");

        btnUpdateForm.setText("UPDATE");
        btnUpdateForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFormActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setText("NIM :");

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnUpdateForm))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblTITLEFORM)))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(193, 193, 193)
                                .addComponent(textNIMu))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(lblNama)
                                .addGap(109, 109, 109)
                                .addComponent(textNamau))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBiologi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBinggris)
                                    .addComponent(lblBindo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFisika)
                                    .addComponent(lblMat)
                                    .addComponent(lblKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textBiou)
                                    .addComponent(textBingu)
                                    .addComponent(textBIu)
                                    .addComponent(textFisu)
                                    .addComponent(textMatu)
                                    .addComponent(textKelasu))))))
                .addContainerGap())
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTITLEFORM)
                .addGap(24, 24, 24)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNIMu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(textNamau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(textKelasu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMat)
                    .addComponent(textMatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFisika)
                    .addComponent(textFisu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindo)
                    .addComponent(textBIu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggris)
                    .addComponent(textBingu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBiologi)
                    .addComponent(textBiou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateForm)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelUpdate);
        panelUpdate.setBounds(450, 10, 430, 450);

        panelDelete.setBackground(new java.awt.Color(242, 238, 229));

        lblFormDelete.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormDelete.setForeground(new java.awt.Color(0, 0, 0));
        lblFormDelete.setText("DELETE FORM");

        lblNamaD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaD.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaD.setText("NIM");

        lblKelasD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasD.setForeground(new java.awt.Color(0, 0, 0));
        lblKelasD.setText("KELAS  :");

        lblMatD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatD.setForeground(new java.awt.Color(0, 0, 0));
        lblMatD.setText("NILAI UN MATEMATIKA :");

        lblFisikaD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblFisikaD.setForeground(new java.awt.Color(0, 0, 0));
        lblFisikaD.setText("NILAI UN FISIKA :");

        lblBindoD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoD.setForeground(new java.awt.Color(0, 0, 0));
        lblBindoD.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisD.setForeground(new java.awt.Color(0, 0, 0));
        lblBinggrisD.setText("NILAI UN BAHASA INGGRIS :");

        lblBiologiD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBiologiD.setForeground(new java.awt.Color(0, 0, 0));
        lblBiologiD.setText("NILAI UN BIOLOGI :");

        btnDeleteForm.setText("DELETE");
        btnDeleteForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblFormDelete))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNamaD))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblFisikaD))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBiologiD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMatD))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKelasD, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBinggrisD))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBindoD, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnDeleteForm)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormDelete)
                .addGap(39, 39, 39)
                .addComponent(lblNamaD)
                .addGap(18, 18, 18)
                .addComponent(lblKelasD)
                .addGap(18, 18, 18)
                .addComponent(lblMatD)
                .addGap(18, 18, 18)
                .addComponent(lblFisikaD)
                .addGap(18, 18, 18)
                .addComponent(lblBindoD)
                .addGap(18, 18, 18)
                .addComponent(lblBinggrisD)
                .addGap(18, 18, 18)
                .addComponent(lblBiologiD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(btnDeleteForm)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelDelete);
        panelDelete.setBounds(455, 12, 430, 440);

        panelUpdateSos.setBackground(new java.awt.Color(242, 238, 229));

        lblTITLESOS.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblTITLESOS.setText("UPDATE FORM");

        lblNamaSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaSos.setText("NAMA SISWA/SISWI :");

        lblKelasSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasSos.setText("KELAS  :");

        lblMatSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatSos.setText("NILAI UN MATEMATIKA :");

        lblIPS.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIPS.setText("NILAI UN IPS :");

        lblBindoSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoSos.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisSos.setText("NILAI UN BAHASA INGGRIS :");

        btnUpdateSos.setText("UPDATE");
        btnUpdateSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSosActionPerformed(evt);
            }
        });

        lblNIMsos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNIMsos.setText("NIM :");

        javax.swing.GroupLayout panelUpdateSosLayout = new javax.swing.GroupLayout(panelUpdateSos);
        panelUpdateSos.setLayout(panelUpdateSosLayout);
        panelUpdateSosLayout.setHorizontalGroup(
            panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateSosLayout.createSequentialGroup()
                        .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnUpdateSos))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblTITLESOS)))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(panelUpdateSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addComponent(lblNIMsos)
                                .addGap(193, 193, 193)
                                .addComponent(textNIMuSos))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addComponent(lblNamaSos)
                                .addGap(109, 109, 109)
                                .addComponent(textNamauSos))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBinggrisSos)
                                    .addComponent(lblBindoSos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIPS)
                                    .addComponent(lblMatSos)
                                    .addComponent(lblKelasSos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textBinguSos)
                                    .addComponent(textBIuSos)
                                    .addComponent(textIPS)
                                    .addComponent(textMatuSos)
                                    .addComponent(textKelasuSos))))))
                .addContainerGap())
        );
        panelUpdateSosLayout.setVerticalGroup(
            panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTITLESOS)
                .addGap(24, 24, 24)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIMsos)
                    .addComponent(textNIMuSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSos)
                    .addComponent(textNamauSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelasSos)
                    .addComponent(textKelasuSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatSos)
                    .addComponent(textMatuSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPS)
                    .addComponent(textIPS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindoSos)
                    .addComponent(textBIuSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggrisSos)
                    .addComponent(textBinguSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnUpdateSos)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelUpdateSos);
        panelUpdateSos.setBounds(450, 10, 430, 450);

        panelDeleteSos.setBackground(new java.awt.Color(242, 238, 229));

        lblFormDeleteSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormDeleteSos.setForeground(new java.awt.Color(0, 0, 0));
        lblFormDeleteSos.setText("DELETE FORM");

        lblNamaDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaDSos.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaDSos.setText("NIM");

        lblKelasDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasDSos.setForeground(new java.awt.Color(0, 0, 0));
        lblKelasDSos.setText("KELAS  :");

        lblMatDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatDSos.setForeground(new java.awt.Color(0, 0, 0));
        lblMatDSos.setText("NILAI UN MATEMATIKA :");

        lblIPSDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIPSDSos.setForeground(new java.awt.Color(0, 0, 0));
        lblIPSDSos.setText("NILAI UN IPS :");

        lblBindoDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoDSos.setForeground(new java.awt.Color(0, 0, 0));
        lblBindoDSos.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisD1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisD1.setForeground(new java.awt.Color(0, 0, 0));
        lblBinggrisD1.setText("NILAI UN BAHASA INGGRIS :");

        btnDeleteFormSos.setText("DELETE");
        btnDeleteFormSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFormSosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteSosLayout = new javax.swing.GroupLayout(panelDeleteSos);
        panelDeleteSos.setLayout(panelDeleteSosLayout);
        panelDeleteSosLayout.setHorizontalGroup(
            panelDeleteSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteSosLayout.createSequentialGroup()
                .addGroup(panelDeleteSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblFormDeleteSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNamaDSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIPSDSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMatDSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKelasDSos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBinggrisD1))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBindoDSos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnDeleteFormSos)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        panelDeleteSosLayout.setVerticalGroup(
            panelDeleteSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteSosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormDeleteSos)
                .addGap(39, 39, 39)
                .addComponent(lblNamaDSos)
                .addGap(18, 18, 18)
                .addComponent(lblKelasDSos)
                .addGap(18, 18, 18)
                .addComponent(lblMatDSos)
                .addGap(18, 18, 18)
                .addComponent(lblIPSDSos)
                .addGap(18, 18, 18)
                .addComponent(lblBindoDSos)
                .addGap(18, 18, 18)
                .addComponent(lblBinggrisD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnDeleteFormSos)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelDeleteSos);
        panelDeleteSos.setBounds(455, 12, 430, 440);

        panelInsertSos.setBackground(new java.awt.Color(242, 238, 229));

        lblFormInsertSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormInsertSos.setText("INSERT FORM");

        lblNamaI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaI1.setText("NAMA SISWA/SISWI :");

        lblKelasI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasI1.setText("KELAS  :");

        lblMatI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatI1.setText("NILAI UN MATEMATIKA :");

        lblUNIPS.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblUNIPS.setText("NILAI UN IPS :");

        lblBindoISos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoISos.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisI1.setText("NILAI UN BAHASA INGGRIS :");

        btnInsertFormSos.setText("INSERT");
        btnInsertFormSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertFormSosActionPerformed(evt);
            }
        });

        lblNIMSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNIMSos.setText("NIM :");

        javax.swing.GroupLayout panelInsertSosLayout = new javax.swing.GroupLayout(panelInsertSos);
        panelInsertSos.setLayout(panelInsertSosLayout);
        panelInsertSosLayout.setHorizontalGroup(
            panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertSosLayout.createSequentialGroup()
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInsertSosLayout.createSequentialGroup()
                        .addComponent(lblKelasI1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMatSos)
                            .addComponent(textKelasSos)
                            .addComponent(textIPSinsert)
                            .addComponent(textBISos)
                            .addComponent(textBingSos)))
                    .addGroup(panelInsertSosLayout.createSequentialGroup()
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaI1)
                            .addComponent(lblNIMSos))
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNamaSos)
                            .addComponent(textNIMSos)))
                    .addGroup(panelInsertSosLayout.createSequentialGroup()
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInsertSosLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblFormInsertSos))
                            .addComponent(lblUNIPS)
                            .addComponent(lblMatI1)
                            .addComponent(lblBinggrisI1)
                            .addComponent(lblBindoISos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelInsertSosLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnInsertFormSos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInsertSosLayout.setVerticalGroup(
            panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertSosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormInsertSos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIMSos)
                    .addComponent(textNIMSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaI1)
                    .addComponent(textNamaSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelasI1)
                    .addComponent(textKelasSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatI1)
                    .addComponent(textMatSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUNIPS)
                    .addComponent(textIPSinsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindoISos)
                    .addComponent(textBISos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggrisI1)
                    .addComponent(textBingSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnInsertFormSos)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelInsertSos);
        panelInsertSos.setBounds(455, 12, 423, 431);

        panelButtonSos.setBackground(new java.awt.Color(242, 238, 229));

        buttonInsertSos.setText("INSERT");
        buttonInsertSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertSosActionPerformed(evt);
            }
        });

        btnShowSos.setText("SHOW");
        btnShowSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSosActionPerformed(evt);
            }
        });

        buttonUpdateSos.setText("UPDATE");
        buttonUpdateSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateSosActionPerformed(evt);
            }
        });

        buttonDeleteSos.setText("DELETE");
        buttonDeleteSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteSosActionPerformed(evt);
            }
        });

        btn_add_student1.setText("Add new Student");
        btn_add_student1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_student1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonSosLayout = new javax.swing.GroupLayout(panelButtonSos);
        panelButtonSos.setLayout(panelButtonSosLayout);
        panelButtonSosLayout.setHorizontalGroup(
            panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonSosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonSosLayout.createSequentialGroup()
                        .addComponent(buttonInsertSos)
                        .addGap(36, 36, 36)
                        .addComponent(btnShowSos)
                        .addGap(38, 38, 38)
                        .addComponent(buttonUpdateSos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(buttonDeleteSos))
                    .addGroup(panelButtonSosLayout.createSequentialGroup()
                        .addComponent(btn_add_student1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelButtonSosLayout.setVerticalGroup(
            panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonSosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsertSos)
                    .addComponent(btnShowSos)
                    .addComponent(buttonUpdateSos)
                    .addComponent(buttonDeleteSos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_add_student1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelAfterLogin.add(panelButtonSos);
        panelButtonSos.setBounds(12, 167, 0, 100);

        PanelAwal.add(panelAfterLogin);
        panelAfterLogin.setBounds(0, 0, 900, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if("".equals(txtName.getText()) || "".equals(new String(txtPass.getPassword()))){
            JOptionPane.showMessageDialog(null, "Please insert your username and password", "Empty Field", JOptionPane.WARNING_MESSAGE);
        }else{
            String username = txtName.getText();
            String password = new String(txtPass.getPassword());
            teach = new TeacherDAO();
            boolean login_success = teach.loginTeacher(username, password);
            if(login_success){
                JOptionPane.showMessageDialog(null, "Login Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                panelLogin.setVisible(false);
                panelAfterLogin.setVisible(true);
                panelInsert.setVisible(false);
                panelUpdate.setVisible(false);
                panelDelete.setVisible(false);
                panelDeleteSos.setVisible(false);
                panelInsertSos.setVisible(false);
                panelUpdateSos.setVisible(false);                
                txtlog_name.setText(teach.getName());
                txtlog_class.setText(teach.getClass_());
                String ehe = txtlog_class.getText();
                //NANTI DIUBAH ARRAY DAN FOR
                 if(ehe.equals("3SC1") || ehe.equals("3SC2") || ehe.equals("3SC3") || ehe.equals("3SC4") || ehe.equals("3SC5") || ehe.equals("3SC6") || ehe.equals("3SC7") || ehe.equals("3SC8")){
                 panelButton.setVisible(true);
                 panelButtonSos.setVisible(false);
                 }else if(ehe.equals("3SO1") || ehe.equals("3SO2") || ehe.equals("3SO3") || ehe.equals("3SO4") || ehe.equals("3SO5") || ehe.equals("3SO6") || ehe.equals("3SO7") || ehe.equals("3SO8")){
                 panelButton.setVisible(true);
                 panelButtonSos.setVisible(true);    
                 }
                txtName.setText("");
                txtPass.setText("");
                
                //delete
                System.out.println("Name : " + teach.getName());
                System.out.println("Class : " + teach.getClass_());
                System.out.println("Username : " + teach.getUsername());
            }else JOptionPane.showMessageDialog(null, "Login Failed, please check your username and password", "Failed", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void btnUpdateFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateFormActionPerformed

    private void btnDeleteFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteFormActionPerformed

    private void btnInsertFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertFormActionPerformed

    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        panelInsert.setVisible(true);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);
        textNama.setText("");
        textKelas.setText("");
        textNIM.setText("");
    }//GEN-LAST:event_buttonInsertActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(true);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);
        textNamau.setText("");
        textKelasu.setText("");
        textNIMu.setText("");
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        panelInsert.setVisible(false);
        panelDelete.setVisible(true);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        showDataStudent();
    }//GEN-LAST:event_btnShowActionPerformed

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        int getrows = tableSiswa.getSelectedRow();
        String status = (tableSiswa.getModel().getValueAt(getrows, 3).toString());
        String nim    = (tableSiswa.getModel().getValueAt(getrows, 0).toString());
        String klas= (tableSiswa.getModel().getValueAt(getrows, 2).toString());
        
        if((status.equals("not updated")&& (klas.equals("3SC1") || klas.equals("3SC2") || klas.equals("3SC3") || klas.equals("3SC4") || klas.equals("3SC5") || klas.equals("3SC6") || klas.equals("3SC7") || klas.equals("3SC8") )) 
                || status.equals("deleted")&& (klas.equals("3SC1") || klas.equals("3SC2") || klas.equals("3SC3") || klas.equals("3SC4") || klas.equals("3SC5") || klas.equals("3SC6") || klas.equals("3SC7") || klas.equals("3SC8") )) {
            panelInsert.setVisible(true);
            panelUpdate.setVisible(false);
            try{
                StudentDAO stud = new StudentDAO();
                ResultSet rs = stud.getbyNIM(nim);
                if(rs.next()){
                    textNIM.setText(rs.getString("nim"));
                    textNIM.setEditable(false);
                    textNama.setText(rs.getString("name"));
                    textKelas.setText(rs.getString("class"));
                }
            }catch(Exception ex){
                System.out.println("Error : " + ex.getMessage());
            }
        }else if(status.equals("not updated")&& (klas.equals("3SO1") || klas.equals("3SO2") || klas.equals("3SO3") || klas.equals("3SO4") || klas.equals("3SO5") || klas.equals("3SO6") || klas.equals("3SO7") || klas.equals("3SO8") )
                || status.equals("deleted")&& (klas.equals("3SO1") || klas.equals("3SO2") || klas.equals("3SO3") || klas.equals("3SO4") || klas.equals("3SO5") || klas.equals("3SO6") || klas.equals("3SO7") || klas.equals("3SO8") ) ){
            
            panelInsert.setVisible(false);
            panelUpdate.setVisible(false);
            panelDeleteSos.setVisible(false);
            panelDelete.setVisible(false);
              panelInsertSos.setVisible(true);
            panelUpdateSos.setVisible(false);
            try{
                StudentDAO stud = new StudentDAO();
                ResultSet rs = stud.getbyNIM(nim);
                if(rs.next()){
                    textNIMSos.setText(rs.getString("nim"));
                    textNIMSos.setEditable(false);
                    textNamaSos.setText(rs.getString("name"));
                    textKelasSos.setText(rs.getString("class"));
                }
            }catch(Exception ex){
                System.out.println("Error : " + ex.getMessage());
            }
            
            
            
        }
        
        
        else if(status.equals("updated")){
            panelInsert.setVisible(false);
            panelUpdate.setVisible(true);
            try{
                StudentDAO stud = new StudentDAO();
                ResultSet rs = stud.getbyNIM(nim);
                if(rs.next()){
                    textNIMu.setText(rs.getString("nim"));
                    textNIMu.setEditable(false);
                    textNamau.setText(rs.getString("name"));
                    textKelasu.setText(rs.getString("class"));
                }
            }catch(Exception ex){
                System.out.println("Error : " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void btn_add_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_studentActionPerformed
        AddStudentForm add = new AddStudentForm();
        add.setVisible(true);
    }//GEN-LAST:event_btn_add_studentActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Logout Confirmation", JOptionPane.OK_CANCEL_OPTION);
        if(choice == JOptionPane.OK_OPTION){
            teach = new TeacherDAO();
            teach.logoutTeacher();
            panelLogin.setVisible(true);
            panelAfterLogin.setVisible(false);
            panelInsert.setVisible(false);
            panelUpdate.setVisible(false);
            panelDelete.setVisible(false);
            txtlog_name.setText("- - -");
            txtlog_class.setText("- - -");
            JOptionPane.showMessageDialog(null, "Logout Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btnUpdateSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSosActionPerformed
         
    }//GEN-LAST:event_btnUpdateSosActionPerformed

    private void btnDeleteFormSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFormSosActionPerformed
        
    }//GEN-LAST:event_btnDeleteFormSosActionPerformed

    private void btnInsertFormSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertFormSosActionPerformed
        
    }//GEN-LAST:event_btnInsertFormSosActionPerformed

    private void buttonInsertSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertSosActionPerformed
  panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(true);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);
    }//GEN-LAST:event_buttonInsertSosActionPerformed

    private void btnShowSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSosActionPerformed
        showDataStudent();
    }//GEN-LAST:event_btnShowSosActionPerformed

    private void buttonUpdateSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateSosActionPerformed
         panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(true);
    }//GEN-LAST:event_buttonUpdateSosActionPerformed

    private void buttonDeleteSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteSosActionPerformed
          panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(true);
        panelUpdateSos.setVisible(false);
    }//GEN-LAST:event_buttonDeleteSosActionPerformed

    private void btn_add_student1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_student1ActionPerformed
        AddStudentForm add = new AddStudentForm();
        add.setVisible(true);
    }//GEN-LAST:event_btn_add_student1ActionPerformed
    
    private DefaultTableModel tabelModelData()
    {      
        String[] namaKolom = {"NIM", "Nama Siswa/Siswi", "Kelas", "Status"};
        int rows = 0;
        try{
            while (rs.next()){
                rows = rs.getRow();
            }
            rs.beforeFirst();
            dataStudent = new String[rows][namaKolom.length];
            for (int i = 0; i < rows; i++) {
                rs.next();
                for (int j = 0; j < namaKolom.length; j++) {
                    dataStudent[i][j] = rs.getString(j + 1);
                }
            }
        } catch (Exception ex){}
        return new DefaultTableModel(dataStudent, namaKolom);
    }


    private void showDataStudent() {
        try {
            stud = new StudentDAO();
            rs = stud.getbyClass(txtlog_class.getText());
            tableSiswa.setModel(tabelModelData());
            tableSiswa.setEnabled(true);
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeRecordsGUI().setVisible(true);    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAwal;
    private javax.swing.JButton btnDeleteForm;
    private javax.swing.JButton btnDeleteFormSos;
    private javax.swing.JButton btnInsertForm;
    private javax.swing.JButton btnInsertFormSos;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnShowSos;
    private javax.swing.JButton btnUpdateForm;
    private javax.swing.JButton btnUpdateSos;
    private javax.swing.JButton btn_add_student;
    private javax.swing.JButton btn_add_student1;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDeleteSos;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonInsertSos;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton buttonUpdateSos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBindo;
    private javax.swing.JLabel lblBindoD;
    private javax.swing.JLabel lblBindoDSos;
    private javax.swing.JLabel lblBindoI;
    private javax.swing.JLabel lblBindoISos;
    private javax.swing.JLabel lblBindoSos;
    private javax.swing.JLabel lblBinggris;
    private javax.swing.JLabel lblBinggrisD;
    private javax.swing.JLabel lblBinggrisD1;
    private javax.swing.JLabel lblBinggrisI;
    private javax.swing.JLabel lblBinggrisI1;
    private javax.swing.JLabel lblBinggrisSos;
    private javax.swing.JLabel lblBiologi;
    private javax.swing.JLabel lblBiologiD;
    private javax.swing.JLabel lblBiologiI;
    private javax.swing.JLabel lblFisika;
    private javax.swing.JLabel lblFisikaD;
    private javax.swing.JLabel lblFisikaI;
    private javax.swing.JLabel lblFormDelete;
    private javax.swing.JLabel lblFormDeleteSos;
    private javax.swing.JLabel lblFormInsert;
    private javax.swing.JLabel lblFormInsertSos;
    private javax.swing.JLabel lblIPS;
    private javax.swing.JLabel lblIPSDSos;
    private javax.swing.JLabel lblIconNama;
    private javax.swing.JLabel lblIconPassword;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKelasD;
    private javax.swing.JLabel lblKelasDSos;
    private javax.swing.JLabel lblKelasI;
    private javax.swing.JLabel lblKelasI1;
    private javax.swing.JLabel lblKelasSos;
    private javax.swing.JLabel lblMat;
    private javax.swing.JLabel lblMatD;
    private javax.swing.JLabel lblMatDSos;
    private javax.swing.JLabel lblMatI;
    private javax.swing.JLabel lblMatI1;
    private javax.swing.JLabel lblMatSos;
    private javax.swing.JLabel lblNIMSos;
    private javax.swing.JLabel lblNIMsos;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaD;
    private javax.swing.JLabel lblNamaDSos;
    private javax.swing.JLabel lblNamaI;
    private javax.swing.JLabel lblNamaI1;
    private javax.swing.JLabel lblNamaSos;
    private javax.swing.JLabel lblTITLEFORM;
    private javax.swing.JLabel lblTITLESOS;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUNIPS;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panelAfterLogin;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelButtonSos;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JPanel panelDeleteSos;
    private javax.swing.JPanel panelFormLogin;
    private javax.swing.JPanel panelIcon;
    private javax.swing.JPanel panelIconAfterLogin;
    private javax.swing.JPanel panelInsert;
    private javax.swing.JPanel panelInsertSos;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelUpdateSos;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JTable tableSiswa;
    private javax.swing.JTextField textBI;
    private javax.swing.JTextField textBISos;
    private javax.swing.JTextField textBIu;
    private javax.swing.JTextField textBIuSos;
    private javax.swing.JTextField textBing;
    private javax.swing.JTextField textBingSos;
    private javax.swing.JTextField textBingu;
    private javax.swing.JTextField textBinguSos;
    private javax.swing.JTextField textBio;
    private javax.swing.JTextField textBiou;
    private javax.swing.JTextField textFis;
    private javax.swing.JTextField textFisu;
    private javax.swing.JTextField textIPS;
    private javax.swing.JTextField textIPSinsert;
    private javax.swing.JTextField textKelas;
    private javax.swing.JTextField textKelasSos;
    private javax.swing.JTextField textKelasu;
    private javax.swing.JTextField textKelasuSos;
    private javax.swing.JTextField textMat;
    private javax.swing.JTextField textMatSos;
    private javax.swing.JTextField textMatu;
    private javax.swing.JTextField textMatuSos;
    private javax.swing.JTextField textNIM;
    private javax.swing.JTextField textNIMSos;
    private javax.swing.JTextField textNIMu;
    private javax.swing.JTextField textNIMuSos;
    private javax.swing.JTextField textNama;
    private javax.swing.JTextField textNamaSos;
    private javax.swing.JTextField textNamau;
    private javax.swing.JTextField textNamauSos;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JLabel txtlog_class;
    private javax.swing.JLabel txtlog_name;
    // End of variables declaration//GEN-END:variables
}
