/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graderecords;
import DBConn.koneksi;
import DBDao.GradeSCDAO;
import DBDao.StudentDAO;
import DBDao.TeacherDAO;
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author J8138
 */
public class GradeRecordsGUI extends javax.swing.JFrame {

    ResultSet rs;
    Connection conn;
    Statement st;
    PreparedStatement prep;
    TeacherDAO teach;
    StudentDAO stud;
    GradeSCDAO grade_sc;
    String[][] dataStudent;
    
    public GradeRecordsGUI() {
        initComponents();        
        panelAfterLogin.show(false);
        panelLogin.show(true);
        conn = new koneksi().setConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAwal = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        panelIcon = new javax.swing.JPanel();
        panelFormLogin = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblIconNama = new javax.swing.JLabel();
        lblIconPassword = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        panelAfterLogin = new javax.swing.JPanel();
        panelIconAfterLogin = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtlog_name = new javax.swing.JLabel();
        txtlog_class = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        panelInsert = new javax.swing.JPanel();
        lblFormInsert = new javax.swing.JLabel();
        lblNamaI = new javax.swing.JLabel();
        lblKelasI = new javax.swing.JLabel();
        lblMatI = new javax.swing.JLabel();
        lblIPAI = new javax.swing.JLabel();
        lblBindoI = new javax.swing.JLabel();
        lblBinggrisI = new javax.swing.JLabel();
        btnInsertForm = new javax.swing.JButton();
        textNamaInsert = new javax.swing.JTextField();
        textKelasInsert = new javax.swing.JTextField();
        textMatInsert = new javax.swing.JTextField();
        textIPAInsert = new javax.swing.JTextField();
        textBIinsert = new javax.swing.JTextField();
        textBingInsert = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textNIMInsert = new javax.swing.JTextField();
        searchInsertButton = new javax.swing.JButton();
        panelButton = new javax.swing.JPanel();
        buttonInsert = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        buttonUpdate = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        btn_add_student = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        scrollPanel = new javax.swing.JScrollPane();
        tableSiswa = new javax.swing.JTable();
        panelUpdate = new javax.swing.JPanel();
        lblTITLEFORM = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblKelas = new javax.swing.JLabel();
        lblMat = new javax.swing.JLabel();
        lblIPAu = new javax.swing.JLabel();
        lblBindo = new javax.swing.JLabel();
        lblBinggris = new javax.swing.JLabel();
        btnUpdateForm = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textNIMUpdate = new javax.swing.JTextField();
        textNamaUpdate = new javax.swing.JTextField();
        textKelasUpdate = new javax.swing.JTextField();
        textMatUpdate = new javax.swing.JTextField();
        txtNilaiIPAUpdate = new javax.swing.JTextField();
        textBIUpdate = new javax.swing.JTextField();
        textBingUpdate = new javax.swing.JTextField();
        btnSearchUpdate = new javax.swing.JButton();
        panelDelete = new javax.swing.JPanel();
        lblFormDelete = new javax.swing.JLabel();
        lblNamaD = new javax.swing.JLabel();
        lblKelasD = new javax.swing.JLabel();
        lblMatD = new javax.swing.JLabel();
        lblIPAD = new javax.swing.JLabel();
        lblBindoD = new javax.swing.JLabel();
        lblBinggrisD = new javax.swing.JLabel();

        btnDeleteForm = new javax.swing.JButton();

        panelUpdateSos = new javax.swing.JPanel();
        lblTITLESOS = new javax.swing.JLabel();
        lblNamaSos = new javax.swing.JLabel();
        lblKelasSos = new javax.swing.JLabel();
        lblMatSos = new javax.swing.JLabel();
        lblIPS = new javax.swing.JLabel();
        lblBindoSos = new javax.swing.JLabel();
        lblBinggrisSos = new javax.swing.JLabel();
        btnUpdateSos = new javax.swing.JButton();
        lblNIMsos = new javax.swing.JLabel();
        textNIMSosUpdate = new javax.swing.JTextField();
        textNamaUpdateSos = new javax.swing.JTextField();
        textKelasUpdateSos = new javax.swing.JTextField();
        textMatUpdateSos = new javax.swing.JTextField();
        textIPSUpdate = new javax.swing.JTextField();
        textBIUpdateSos = new javax.swing.JTextField();
        textBingUpdateSos = new javax.swing.JTextField();
        btnSearchUpdateSOS = new javax.swing.JButton();
        panelDeleteSos = new javax.swing.JPanel();
        lblFormDeleteSos = new javax.swing.JLabel();
        lblNamaDSos = new javax.swing.JLabel();
        lblKelasDSos = new javax.swing.JLabel();
        lblMatDSos = new javax.swing.JLabel();
        lblIPSDSos = new javax.swing.JLabel();
        lblBindoDSos = new javax.swing.JLabel();
        lblBinggrisD1 = new javax.swing.JLabel();
        btnDeleteFormSos = new javax.swing.JButton();
        panelInsertSos = new javax.swing.JPanel();
        lblFormInsertSos = new javax.swing.JLabel();
        lblNamaI1 = new javax.swing.JLabel();
        lblKelasI1 = new javax.swing.JLabel();
        lblMatI1 = new javax.swing.JLabel();
        lblUNIPS = new javax.swing.JLabel();
        lblBindoISos = new javax.swing.JLabel();
        lblBinggrisI1 = new javax.swing.JLabel();
        btnInsertFormSos = new javax.swing.JButton();
        textNamaSosInsert = new javax.swing.JTextField();
        textKelasSosInsert = new javax.swing.JTextField();
        textMatSosInsert = new javax.swing.JTextField();
        textIPSinsert = new javax.swing.JTextField();
        textBISosInsert = new javax.swing.JTextField();
        textBingSosInsert = new javax.swing.JTextField();
        lblNIMSos = new javax.swing.JLabel();
        textNIMSosInsert = new javax.swing.JTextField();
        searchButtonInsert = new javax.swing.JButton();
        panelButtonSos = new javax.swing.JPanel();
        buttonInsertSos = new javax.swing.JButton();
        btnShowSos = new javax.swing.JButton();
        buttonUpdateSos = new javax.swing.JButton();
        buttonDeleteSos = new javax.swing.JButton();
        btn_add_student1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelAwal.setBackground(new java.awt.Color(255, 255, 255));
        PanelAwal.setLayout(null);

        panelLogin.setBackground(new java.awt.Color(242, 238, 229));
        panelLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(194, 232, 206), 10));
        panelLogin.setLayout(null);

        panelIcon.setBackground(new java.awt.Color(194, 232, 206));

        javax.swing.GroupLayout panelIconLayout = new javax.swing.GroupLayout(panelIcon);
        panelIcon.setLayout(panelIconLayout);
        panelIconLayout.setHorizontalGroup(
            panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        panelIconLayout.setVerticalGroup(
            panelIconLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );

        panelLogin.add(panelIcon);
        panelIcon.setBounds(20, 20, 840, 160);

        panelFormLogin.setBackground(new java.awt.Color(194, 232, 206));

        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTitle.setText("LOGIN FORM");

        lblIconNama.setBackground(new java.awt.Color(255, 255, 255));
        lblIconNama.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblIconNama.setText("USERNAME :");

        lblIconPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblIconPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblIconPassword.setText("PASSWORD :");

        txtName.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        txtPass.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        loginButton.setBackground(new java.awt.Color(255, 255, 255));
        loginButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        loginButton.setText("LOGIN");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelFormLoginLayout = new javax.swing.GroupLayout(panelFormLogin);
        panelFormLogin.setLayout(panelFormLoginLayout);
        panelFormLoginLayout.setHorizontalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelFormLoginLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblIconPassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIconNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelFormLoginLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(lblTitle))
                    .addGroup(panelFormLoginLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        panelFormLoginLayout.setVerticalGroup(
            panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFormLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(33, 33, 33)
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIconNama)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(panelFormLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIconPassword)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(loginButton)
                .addContainerGap())
        );

        panelLogin.add(panelFormLogin);
        panelFormLogin.setBounds(20, 200, 840, 230);

        PanelAwal.add(panelLogin);
        panelLogin.setBounds(0, 0, 880, 460);

        panelAfterLogin.setBackground(new java.awt.Color(194, 232, 206));
        panelAfterLogin.setMinimumSize(new java.awt.Dimension(680, 450));
        panelAfterLogin.setLayout(null);

        panelIconAfterLogin.setBackground(new java.awt.Color(242, 238, 229));
        panelIconAfterLogin.setPreferredSize(new java.awt.Dimension(427, 141));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Logged in as : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Class :");

        txtlog_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlog_name.setText("- - -");

        txtlog_class.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtlog_class.setText("- - -");

        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIconAfterLoginLayout = new javax.swing.GroupLayout(panelIconAfterLogin);
        panelIconAfterLogin.setLayout(panelIconAfterLoginLayout);
        panelIconAfterLoginLayout.setHorizontalGroup(
            panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconAfterLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIconAfterLoginLayout.createSequentialGroup()
                        .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlog_class)
                            .addComponent(txtlog_name)))
                    .addComponent(btn_logout))
                .addContainerGap(296, Short.MAX_VALUE))
        );
        panelIconAfterLoginLayout.setVerticalGroup(
            panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIconAfterLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtlog_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIconAfterLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtlog_class))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_logout)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelAfterLogin.add(panelIconAfterLogin);
        panelIconAfterLogin.setBounds(12, 12, 425, 141);

        panelInsert.setBackground(new java.awt.Color(242, 238, 229));

        lblFormInsert.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormInsert.setForeground(new java.awt.Color(0, 0, 0));
        lblFormInsert.setText("INSERT FORM");

        lblNamaI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaI.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaI.setText("NAMA SISWA/SISWI :");

        lblKelasI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasI.setForeground(new java.awt.Color(0, 0, 0));
        lblKelasI.setText("KELAS  :");

        lblMatI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatI.setForeground(new java.awt.Color(0, 0, 0));
        lblMatI.setText("NILAI UN MATEMATIKA :");

        lblIPAI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIPAI.setForeground(new java.awt.Color(0, 0, 0));
        lblIPAI.setText("NILAI UN IPA :");

        lblBindoI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoI.setForeground(new java.awt.Color(0, 0, 0));
        lblBindoI.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisI.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisI.setForeground(new java.awt.Color(0, 0, 0));
        lblBinggrisI.setText("NILAI UN BAHASA INGGRIS :");

        btnInsertForm.setText("INSERT");
        btnInsertForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertFormActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NIM :");

        searchInsertButton.setText("SEARCH");

        javax.swing.GroupLayout panelInsertLayout = new javax.swing.GroupLayout(panelInsert);
        panelInsert.setLayout(panelInsertLayout);
        panelInsertLayout.setHorizontalGroup(
            panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertLayout.createSequentialGroup()
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInsertLayout.createSequentialGroup()
                        .addComponent(lblKelasI, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMatInsert)
                            .addComponent(textKelasInsert)
                            .addComponent(textIPAInsert)
                            .addComponent(textBIinsert)
                            .addComponent(textBingInsert)))
                    .addGroup(panelInsertLayout.createSequentialGroup()
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaI)
                            .addComponent(jLabel1))
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNamaInsert)
                            .addComponent(textNIMInsert)))
                    .addGroup(panelInsertLayout.createSequentialGroup()
                        .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInsertLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblFormInsert))
                            .addComponent(lblIPAI)
                            .addComponent(lblMatI)
                            .addComponent(lblBinggrisI)
                            .addComponent(lblBindoI, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelInsertLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnInsertForm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInsertLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchInsertButton)
                .addGap(80, 80, 80))
        );
        panelInsertLayout.setVerticalGroup(
            panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textNIMInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchInsertButton)
                .addGap(10, 10, 10)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaI)
                    .addComponent(textNamaInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelasI)
                    .addComponent(textKelasInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatI)
                    .addComponent(textMatInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAI)
                    .addComponent(textIPAInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindoI)
                    .addComponent(textBIinsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggrisI)
                    .addComponent(textBingInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnInsertForm)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelInsert);
        panelInsert.setBounds(455, 12, 421, 436);

        panelButton.setBackground(new java.awt.Color(242, 238, 229));

        buttonInsert.setText("INSERT");
        buttonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertActionPerformed(evt);
            }
        });

        btnShow.setText("SHOW");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        buttonUpdate.setText("UPDATE");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonDelete.setText("DELETE");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        btn_add_student.setText("Add new Student");
        btn_add_student.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_studentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonLayout = new javax.swing.GroupLayout(panelButton);
        panelButton.setLayout(panelButtonLayout);
        panelButtonLayout.setHorizontalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonLayout.createSequentialGroup()
                        .addComponent(buttonInsert)
                        .addGap(36, 36, 36)
                        .addComponent(btnShow)
                        .addGap(38, 38, 38)
                        .addComponent(buttonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(buttonDelete))
                    .addGroup(panelButtonLayout.createSequentialGroup()
                        .addComponent(btn_add_student, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelButtonLayout.setVerticalGroup(
            panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsert)
                    .addComponent(btnShow)
                    .addComponent(buttonUpdate)
                    .addComponent(buttonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_add_student)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelAfterLogin.add(panelButton);
        panelButton.setBounds(12, 167, 420, 100);

        panelTable.setBackground(new java.awt.Color(242, 238, 229));

        scrollPanel.setBackground(new java.awt.Color(242, 238, 229));

        tableSiswa.setBackground(new java.awt.Color(242, 238, 229));
        tableSiswa.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        tableSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama Siswa/Siswi", "Kelas", "Status"
            }
        ));
        tableSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSiswaMouseClicked(evt);
            }
        });
        scrollPanel.setViewportView(tableSiswa);

        javax.swing.GroupLayout panelTableLayout = new javax.swing.GroupLayout(panelTable);
        panelTable.setLayout(panelTableLayout);
        panelTableLayout.setHorizontalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        panelTableLayout.setVerticalGroup(
            panelTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );

        panelAfterLogin.add(panelTable);
        panelTable.setBounds(12, 273, 425, 185);

        panelUpdate.setBackground(new java.awt.Color(242, 238, 229));

        lblTITLEFORM.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblTITLEFORM.setForeground(new java.awt.Color(0, 0, 0));
        lblTITLEFORM.setText("UPDATE FORM");

        lblNama.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNama.setForeground(new java.awt.Color(0, 0, 0));
        lblNama.setText("NAMA SISWA/SISWI :");

        lblKelas.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelas.setForeground(new java.awt.Color(0, 0, 0));
        lblKelas.setText("KELAS  :");

        lblMat.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMat.setForeground(new java.awt.Color(0, 0, 0));
        lblMat.setText("NILAI UN MATEMATIKA :");

        lblIPAu.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIPAu.setForeground(new java.awt.Color(0, 0, 0));
        lblIPAu.setText("NILAI UN IPA :");

        lblBindo.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindo.setForeground(new java.awt.Color(0, 0, 0));
        lblBindo.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggris.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggris.setForeground(new java.awt.Color(0, 0, 0));
        lblBinggris.setText("NILAI UN BAHASA INGGRIS :");

        btnUpdateForm.setText("UPDATE");
        btnUpdateForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFormActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NIM :");

        btnSearchUpdate.setText("SEARCH");

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnUpdateForm))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblTITLEFORM)))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(panelUpdateLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(193, 193, 193)
                                .addComponent(textNIMUpdate))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addComponent(lblNama)
                                .addGap(109, 109, 109)
                                .addComponent(textNamaUpdate))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBinggris)
                                    .addComponent(lblBindo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIPAu)
                                    .addComponent(lblMat)
                                    .addComponent(lblKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelUpdateLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textBingUpdate)
                                    .addComponent(textBIUpdate)
                                    .addComponent(txtNilaiIPAUpdate)
                                    .addComponent(textMatUpdate)
                                    .addComponent(textKelasUpdate))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearchUpdate)
                .addGap(69, 69, 69))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTITLEFORM)
                .addGap(24, 24, 24)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNIMUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnSearchUpdate)
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(textNamaUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelas)
                    .addComponent(textKelasUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMat)
                    .addComponent(textMatUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAu)
                    .addComponent(txtNilaiIPAUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindo)
                    .addComponent(textBIUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggris)
                    .addComponent(textBingUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateForm)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelUpdate);
        panelUpdate.setBounds(450, 10, 430, 450);

        panelDelete.setBackground(new java.awt.Color(242, 238, 229));

        lblFormDelete.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormDelete.setText("DELETE FORM");

        lblNamaD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaD.setText("NIM");

        lblKelasD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasD.setText("KELAS  :");

        lblMatD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatD.setText("NILAI UN MATEMATIKA :");


        lblIPAD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIPAD.setForeground(new java.awt.Color(0, 0, 0));
        lblIPAD.setText("NILAI UN IPA :");


        lblBindoD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoD.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisD.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisD.setText("NILAI UN BAHASA INGGRIS :");


        btnDeleteForm.setText("DELETE");
        btnDeleteForm.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        txt_class.setText("- - -");

        txt_mtk.setText("- - -");

        txt_ipa.setText("- - -");

        txt_indo.setText("- - -");

        txt_eng.setText("- - -");

        lblKelasD1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasD1.setText("Nama : ");

        txt_name.setText("- - -");

        btn_cancel.setText("Cancel");
        btn_cancel.setEnabled(false);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteLayout = new javax.swing.GroupLayout(panelDelete);
        panelDelete.setLayout(panelDeleteLayout);
        panelDeleteLayout.setHorizontalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteLayout.createSequentialGroup()

                        .addGap(130, 130, 130)
                        .addComponent(lblFormDelete))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNamaD))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIPAD))

                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblFormDelete)
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_search)
                .addGap(27, 27, 27))
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addComponent(lblMatD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ipa)
                            .addComponent(txt_mtk)))
                    .addComponent(lblFisikaD)
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addComponent(lblKelasD, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_class))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addComponent(lblKelasD1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_name))
                    .addGroup(panelDeleteLayout.createSequentialGroup()
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_delete)
                            .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblBindoD, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBinggrisD)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_eng)
                            .addComponent(txt_indo)
                            .addComponent(btn_cancel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDeleteLayout.setVerticalGroup(
            panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormDelete)

                .addGap(39, 39, 39)
                .addComponent(lblNamaD)
                .addGap(18, 18, 18)
                .addComponent(lblKelasD)
                .addGap(18, 18, 18)
                .addComponent(lblMatD)
                .addGap(18, 18, 18)
                .addComponent(lblIPAD)

                .addGap(18, 18, 18)
                .addGroup(panelDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFisikaD)
                    .addComponent(txt_ipa))
                .addGap(18, 18, 18)

                .addComponent(lblBinggrisD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnDeleteForm)

                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelDelete);
        panelDelete.setBounds(455, 12, 430, 440);

        panelUpdateSos.setBackground(new java.awt.Color(242, 238, 229));

        lblTITLESOS.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblTITLESOS.setForeground(new java.awt.Color(0, 0, 0));
        lblTITLESOS.setText("UPDATE FORM");

        lblNamaSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaSos.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaSos.setText("NAMA SISWA/SISWI :");

        lblKelasSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasSos.setForeground(new java.awt.Color(0, 0, 0));
        lblKelasSos.setText("KELAS  :");

        lblMatSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatSos.setForeground(new java.awt.Color(0, 0, 0));
        lblMatSos.setText("NILAI UN MATEMATIKA :");

        lblIPS.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIPS.setForeground(new java.awt.Color(0, 0, 0));
        lblIPS.setText("NILAI UN IPS :");

        lblBindoSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoSos.setForeground(new java.awt.Color(0, 0, 0));
        lblBindoSos.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisSos.setForeground(new java.awt.Color(0, 0, 0));
        lblBinggrisSos.setText("NILAI UN BAHASA INGGRIS :");

        btnUpdateSos.setText("UPDATE");
        btnUpdateSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSosActionPerformed(evt);
            }
        });

        lblNIMsos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNIMsos.setForeground(new java.awt.Color(0, 0, 0));
        lblNIMsos.setText("NIM :");

        btnSearchUpdateSOS.setText("SEARCH");

        javax.swing.GroupLayout panelUpdateSosLayout = new javax.swing.GroupLayout(panelUpdateSos);
        panelUpdateSos.setLayout(panelUpdateSosLayout);
        panelUpdateSosLayout.setHorizontalGroup(
            panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateSosLayout.createSequentialGroup()
                        .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnUpdateSos))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblTITLESOS)))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addGroup(panelUpdateSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addComponent(lblNIMsos)
                                .addGap(193, 193, 193)
                                .addComponent(textNIMSosUpdate))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addComponent(lblNamaSos)
                                .addGap(109, 109, 109)
                                .addComponent(textNamaUpdateSos))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBinggrisSos)
                                    .addComponent(lblBindoSos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIPS)
                                    .addComponent(lblMatSos)
                                    .addComponent(lblKelasSos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textBingUpdateSos)
                                    .addComponent(textBIUpdateSos)
                                    .addComponent(textIPSUpdate)
                                    .addComponent(textMatUpdateSos)
                                    .addComponent(textKelasUpdateSos))))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateSosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnSearchUpdateSOS)
                .addGap(67, 67, 67))
        );
        panelUpdateSosLayout.setVerticalGroup(
            panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateSosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTITLESOS)
                .addGap(24, 24, 24)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIMsos)
                    .addComponent(textNIMSosUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearchUpdateSOS)
                .addGap(15, 15, 15)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaSos)
                    .addComponent(textNamaUpdateSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelasSos)
                    .addComponent(textKelasUpdateSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatSos)
                    .addComponent(textMatUpdateSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPS)
                    .addComponent(textIPSUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindoSos)
                    .addComponent(textBIUpdateSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUpdateSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggrisSos)
                    .addComponent(textBingUpdateSos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnUpdateSos)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelUpdateSos);
        panelUpdateSos.setBounds(450, 10, 430, 450);

        panelDeleteSos.setBackground(new java.awt.Color(242, 238, 229));

        lblFormDeleteSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormDeleteSos.setText("DELETE FORM");

        lblNamaDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaDSos.setText("NIM");

        lblKelasDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasDSos.setText("KELAS  :");

        lblMatDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatDSos.setText("NILAI UN MATEMATIKA :");

        lblIPSDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIPSDSos.setText("NILAI UN IPS :");

        lblBindoDSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoDSos.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisD1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisD1.setText("NILAI UN BAHASA INGGRIS :");

        btnDeleteFormSos.setText("DELETE");
        btnDeleteFormSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFormSosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDeleteSosLayout = new javax.swing.GroupLayout(panelDeleteSos);
        panelDeleteSos.setLayout(panelDeleteSosLayout);
        panelDeleteSosLayout.setHorizontalGroup(
            panelDeleteSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteSosLayout.createSequentialGroup()
                .addGroup(panelDeleteSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblFormDeleteSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNamaDSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblIPSDSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblMatDSos))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblKelasDSos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBinggrisD1))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBindoDSos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDeleteSosLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnDeleteFormSos)))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        panelDeleteSosLayout.setVerticalGroup(
            panelDeleteSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteSosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormDeleteSos)
                .addGap(39, 39, 39)
                .addComponent(lblNamaDSos)
                .addGap(18, 18, 18)
                .addComponent(lblKelasDSos)
                .addGap(18, 18, 18)
                .addComponent(lblMatDSos)
                .addGap(18, 18, 18)
                .addComponent(lblIPSDSos)
                .addGap(18, 18, 18)
                .addComponent(lblBindoDSos)
                .addGap(18, 18, 18)
                .addComponent(lblBinggrisD1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(btnDeleteFormSos)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelDeleteSos);
        panelDeleteSos.setBounds(455, 12, 430, 440);

        panelInsertSos.setBackground(new java.awt.Color(242, 238, 229));

        lblFormInsertSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        lblFormInsertSos.setForeground(new java.awt.Color(0, 0, 0));
        lblFormInsertSos.setText("INSERT FORM");

        lblNamaI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNamaI1.setForeground(new java.awt.Color(0, 0, 0));
        lblNamaI1.setText("NAMA SISWA/SISWI :");

        lblKelasI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblKelasI1.setForeground(new java.awt.Color(0, 0, 0));
        lblKelasI1.setText("KELAS  :");

        lblMatI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMatI1.setForeground(new java.awt.Color(0, 0, 0));
        lblMatI1.setText("NILAI UN MATEMATIKA :");

        lblUNIPS.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblUNIPS.setForeground(new java.awt.Color(0, 0, 0));
        lblUNIPS.setText("NILAI UN IPS :");

        lblBindoISos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBindoISos.setForeground(new java.awt.Color(0, 0, 0));
        lblBindoISos.setText("NILAI UN BAHASA INDONESIA :");

        lblBinggrisI1.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblBinggrisI1.setForeground(new java.awt.Color(0, 0, 0));
        lblBinggrisI1.setText("NILAI UN BAHASA INGGRIS :");

        btnInsertFormSos.setText("INSERT");
        btnInsertFormSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertFormSosActionPerformed(evt);
            }
        });

        lblNIMSos.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblNIMSos.setForeground(new java.awt.Color(0, 0, 0));
        lblNIMSos.setText("NIM :");

        searchButtonInsert.setText("SEARCH");

        javax.swing.GroupLayout panelInsertSosLayout = new javax.swing.GroupLayout(panelInsertSos);
        panelInsertSos.setLayout(panelInsertSosLayout);
        panelInsertSosLayout.setHorizontalGroup(
            panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertSosLayout.createSequentialGroup()
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInsertSosLayout.createSequentialGroup()
                        .addComponent(lblKelasI1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textMatSosInsert)
                            .addComponent(textKelasSosInsert)
                            .addComponent(textIPSinsert)
                            .addComponent(textBISosInsert)
                            .addComponent(textBingSosInsert)))
                    .addGroup(panelInsertSosLayout.createSequentialGroup()
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamaI1)
                            .addComponent(lblNIMSos))
                        .addGap(86, 86, 86)
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textNamaSosInsert)
                            .addComponent(textNIMSosInsert)))
                    .addGroup(panelInsertSosLayout.createSequentialGroup()
                        .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInsertSosLayout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(lblFormInsertSos))
                            .addComponent(lblUNIPS)
                            .addComponent(lblMatI1)
                            .addComponent(lblBinggrisI1)
                            .addComponent(lblBindoISos, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 132, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelInsertSosLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(btnInsertFormSos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInsertSosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchButtonInsert)
                .addGap(85, 85, 85))
        );
        panelInsertSosLayout.setVerticalGroup(
            panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsertSosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblFormInsertSos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNIMSos)
                    .addComponent(textNIMSosInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButtonInsert)
                .addGap(15, 15, 15)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaI1)
                    .addComponent(textNamaSosInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKelasI1)
                    .addComponent(textKelasSosInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatI1)
                    .addComponent(textMatSosInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUNIPS)
                    .addComponent(textIPSinsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBindoISos)
                    .addComponent(textBISosInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInsertSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBinggrisI1)
                    .addComponent(textBingSosInsert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnInsertFormSos)
                .addGap(51, 51, 51))
        );

        panelAfterLogin.add(panelInsertSos);
        panelInsertSos.setBounds(455, 12, 421, 435);

        panelButtonSos.setBackground(new java.awt.Color(242, 238, 229));

        buttonInsertSos.setText("INSERT");
        buttonInsertSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonInsertSosActionPerformed(evt);
            }
        });

        btnShowSos.setText("SHOW");
        btnShowSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowSosActionPerformed(evt);
            }
        });

        buttonUpdateSos.setText("UPDATE");
        buttonUpdateSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateSosActionPerformed(evt);
            }
        });

        buttonDeleteSos.setText("DELETE");
        buttonDeleteSos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteSosActionPerformed(evt);
            }
        });

        btn_add_student1.setText("Add new Student");
        btn_add_student1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_student1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelButtonSosLayout = new javax.swing.GroupLayout(panelButtonSos);
        panelButtonSos.setLayout(panelButtonSosLayout);
        panelButtonSosLayout.setHorizontalGroup(
            panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelButtonSosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelButtonSosLayout.createSequentialGroup()
                        .addComponent(buttonInsertSos)
                        .addGap(36, 36, 36)
                        .addComponent(btnShowSos)
                        .addGap(38, 38, 38)
                        .addComponent(buttonUpdateSos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(buttonDeleteSos))
                    .addGroup(panelButtonSosLayout.createSequentialGroup()
                        .addComponent(btn_add_student1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelButtonSosLayout.setVerticalGroup(
            panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelButtonSosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelButtonSosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonInsertSos)
                    .addComponent(btnShowSos)
                    .addComponent(buttonUpdateSos)
                    .addComponent(buttonDeleteSos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_add_student1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        panelAfterLogin.add(panelButtonSos);

        panelButtonSos.setBounds(12, 167, 425, 100);


        PanelAwal.add(panelAfterLogin);
        panelAfterLogin.setBounds(0, 0, 900, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 878, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        if("".equals(txtName.getText()) || "".equals(new String(txtPass.getPassword()))){
            JOptionPane.showMessageDialog(null, "Please insert your username and password", "Empty Field", JOptionPane.WARNING_MESSAGE);
        }else{
            String username = txtName.getText();
            String password = new String(txtPass.getPassword());
            teach = new TeacherDAO();
            boolean login_success = teach.loginTeacher(username, password);
            if(login_success){
                JOptionPane.showMessageDialog(null, "Login Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
                panelLogin.setVisible(false);
                panelAfterLogin.setVisible(true);
                panelInsert.setVisible(false);
                panelUpdate.setVisible(false);
                panelDelete.setVisible(false);
                panelDeleteSos.setVisible(false);
                panelInsertSos.setVisible(false);
                panelUpdateSos.setVisible(false);                
                txtlog_name.setText(teach.getName());
                txtlog_class.setText(teach.getClass_());
                String ehe = txtlog_class.getText();
                //NANTI DIUBAH ARRAY DAN FOR
                 if(ehe.equals("3SC1") || ehe.equals("3SC2") || ehe.equals("3SC3") || ehe.equals("3SC4") || ehe.equals("3SC5") || ehe.equals("3SC6") || ehe.equals("3SC7") || ehe.equals("3SC8")){
                 panelButton.setVisible(true);
                 panelButtonSos.setVisible(false);
                 }else if(ehe.equals("3SO1") || ehe.equals("3SO2") || ehe.equals("3SO3") || ehe.equals("3SO4") || ehe.equals("3SO5") || ehe.equals("3SO6") || ehe.equals("3SO7") || ehe.equals("3SO8")){
                 panelButton.setVisible(false);
                 panelButtonSos.setVisible(true);    
                 }
                txtName.setText("");
                txtPass.setText("");
                
                //delete
                System.out.println("Name : " + teach.getName());
                System.out.println("Class : " + teach.getClass_());
                System.out.println("Username : " + teach.getUsername());
            }else JOptionPane.showMessageDialog(null, "Login Failed, please check your username and password", "Failed", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void btnUpdateFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateFormActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int choice_ok = JOptionPane.showConfirmDialog(null, "Sure to delete this Grade data ?", "Delete Confirmation", JOptionPane.OK_CANCEL_OPTION);
        if(choice_ok == JOptionPane.OK_OPTION){
            String nim = txt_nim.getText();
            grade_sc = new GradeSCDAO();
            boolean success = grade_sc.deleteGradeByNim(nim);
            if(success){
                JOptionPane.showMessageDialog(null, "Grade deleted Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                canceldeletion();
                showDataStudent();
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btnInsertFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertFormActionPerformed

    private void buttonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertActionPerformed
        panelInsert.setVisible(true);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);

        textNamaInsert.setText("");
        textKelasInsert.setText("");
        textNIMInsert.setText("");
        textNIMInsert.setEditable(true);
        textNamaInsert.setEditable(false);
        textKelasInsert.setEditable(false);
        textMatInsert.setEditable(false);
        textIPAInsert.setEditable(false);
        textBIinsert.setEditable(false);
        textBingInsert.setEditable(false);

    }//GEN-LAST:event_buttonInsertActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(true);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);
        textNamaUpdate.setText("");
        textKelasUpdate.setText("");
        textNIMUpdate.setText("");
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        panelInsert.setVisible(false);
        panelDelete.setVisible(true);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);
        canceldeletion();
    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        showDataStudent();
    }//GEN-LAST:event_btnShowActionPerformed

    private void tableSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSiswaMouseClicked
        int getrows = tableSiswa.getSelectedRow();
        String status = (tableSiswa.getModel().getValueAt(getrows, 3).toString());
        String nim    = (tableSiswa.getModel().getValueAt(getrows, 0).toString());
        String klas= (tableSiswa.getModel().getValueAt(getrows, 2).toString());
        
        if((status.equals("not updated")&& (klas.equals("3SC1") || klas.equals("3SC2") || klas.equals("3SC3") || klas.equals("3SC4") || klas.equals("3SC5") || klas.equals("3SC6") || klas.equals("3SC7") || klas.equals("3SC8") )) 
                || status.equals("deleted")&& (klas.equals("3SC1") || klas.equals("3SC2") || klas.equals("3SC3") || klas.equals("3SC4") || klas.equals("3SC5") || klas.equals("3SC6") || klas.equals("3SC7") || klas.equals("3SC8") )) {
            panelInsert.setVisible(true);            
            try{
                StudentDAO stud = new StudentDAO();
                ResultSet rs = stud.getbyNIM(nim);
                if(rs.next()){
                    textNIMInsert.setText(rs.getString("nim"));
                    textNIMInsert.setEditable(false);
                    textNamaInsert.setText(rs.getString("name"));
                    textKelasInsert.setText(rs.getString("class"));
                     textNamaInsert.setEditable(true);
        textKelasInsert.setEditable(true);
        textMatInsert.setEditable(true);
        textIPAInsert.setEditable(true);
        textBIinsert.setEditable(true);
        textBingInsert.setEditable(true);
            panelUpdate.setVisible(false);
                }
            }catch(Exception ex){
                System.out.println("Error : " + ex.getMessage());
            }
        }else if(status.equals("not updated")&& (klas.equals("3SO1") || klas.equals("3SO2") || klas.equals("3SO3") || klas.equals("3SO4") || klas.equals("3SO5") || klas.equals("3SO6") || klas.equals("3SO7") || klas.equals("3SO8") )
                || status.equals("deleted")&& (klas.equals("3SO1") || klas.equals("3SO2") || klas.equals("3SO3") || klas.equals("3SO4") || klas.equals("3SO5") || klas.equals("3SO6") || klas.equals("3SO7") || klas.equals("3SO8") ) ){
            
            panelInsert.setVisible(false);
            panelUpdate.setVisible(false);
            panelDeleteSos.setVisible(false);
            panelDelete.setVisible(false);
            panelButton.setVisible(false);
            panelButtonSos.setVisible(true);
            panelInsertSos.setVisible(true);
            panelUpdateSos.setVisible(false);
            try{
                StudentDAO stud = new StudentDAO();
                ResultSet rs = stud.getbyNIM(nim);
                if(rs.next()){
                    textNIMSosInsert.setText(rs.getString("nim"));
                    textNIMSosInsert.setEditable(false);
                    textNamaSosInsert.setText(rs.getString("name"));
                    textKelasSosInsert.setText(rs.getString("class"));
                     textNIMSosInsert.setEditable(true);
        textNamaSosInsert.setEditable(true);
        textKelasSosInsert.setEditable(true);
        textMatSosInsert.setEditable(true);
        textIPSinsert.setEditable(true);
        textBISosInsert.setEditable(true);
        textBingSosInsert.setEditable(true);
        panelUpdateSos.setVisible(false);
                }
            }catch(Exception ex){
                System.out.println("Error : " + ex.getMessage());
            }
            
            
            
        }
        
        
        else if(status.equals("updated")&& (klas.equals("3SC1") || klas.equals("3SC2") || klas.equals("3SC3") || klas.equals("3SC4") || klas.equals("3SC5") || klas.equals("3SC6") || klas.equals("3SC7") || klas.equals("3SC8")) ){
            panelInsertSos.setVisible(false);
            panelUpdateSos.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteSos.setVisible(false);
            panelInsert.setVisible(false);
            panelUpdate.setVisible(true);            
            try{
                StudentDAO stud = new StudentDAO();
                ResultSet rs = stud.getbyNIM(nim);
                if(rs.next()){
                    textNIMUpdate.setText(rs.getString("nim"));
                    textNIMUpdate.setEditable(false);
                    textNamaUpdate.setText(rs.getString("name"));
                    textKelasUpdate.setText(rs.getString("class"));
                     textNamaUpdate.setEditable(true);
        textKelasUpdate.setEditable(true);
        textMatUpdate.setEditable(true);
        txtNilaiIPAUpdate.setEditable(true);
        textBIUpdate.setEditable(true);
        textBingUpdate.setEditable(true);
                }
            }catch(Exception ex){
                System.out.println("Error : " + ex.getMessage());
            }
        }
        else if(status.equals("updated")&& (klas.equals("3SO1") || klas.equals("3SO2") || klas.equals("3SO3") || klas.equals("3SO4") || klas.equals("3SO5") || klas.equals("3SO6") || klas.equals("3SO7") || klas.equals("3SO8") )){
             panelInsert.setVisible(false);
            panelUpdate.setVisible(false);
            panelInsertSos.setVisible(false);
            panelDelete.setVisible(false);
            panelDeleteSos.setVisible(false);
            panelUpdateSos.setVisible(true);
             try{
                StudentDAO stud = new StudentDAO();
                ResultSet rs = stud.getbyNIM(nim);
                if(rs.next()){
                    textNIMSosUpdate.setText(rs.getString("nim"));
                    textNIMSosUpdate.setEditable(false);
                    textNamaUpdateSos.setText(rs.getString("name"));
                    textKelasUpdateSos.setText(rs.getString("class"));
                     textNamaUpdate.setEditable(true);
        textKelasUpdateSos.setEditable(true);
        textMatUpdateSos.setEditable(true);
        textIPSUpdate.setEditable(true);
        textBIUpdateSos.setEditable(true);
        textBingUpdateSos.setEditable(true);
                }
            }catch(Exception ex){
                System.out.println("Error : " + ex.getMessage());
            }
            
        }
    }//GEN-LAST:event_tableSiswaMouseClicked

    private void btn_add_studentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_studentActionPerformed
        AddStudentForm add = new AddStudentForm();
        add.txt_class.setText(txtlog_class.getText());
        add.setVisible(true);
    }//GEN-LAST:event_btn_add_studentActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Do you really want to logout?", "Logout Confirmation", JOptionPane.OK_CANCEL_OPTION);
        DefaultTableModel model_logout = new DefaultTableModel();
        if(choice == JOptionPane.OK_OPTION){
            teach = new TeacherDAO();
            teach.logoutTeacher();
            panelLogin.setVisible(true);
            panelAfterLogin.setVisible(false);
            panelInsert.setVisible(false);
            panelUpdate.setVisible(false);
            panelDelete.setVisible(false);
            tableSiswa.setModel(model_logout);
            txtlog_name.setText("- - -");
            txtlog_class.setText("- - -");
            JOptionPane.showMessageDialog(null, "Logout Successful", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btnUpdateSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSosActionPerformed
         
    }//GEN-LAST:event_btnUpdateSosActionPerformed

    private void btnDeleteFormSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFormSosActionPerformed
        
    }//GEN-LAST:event_btnDeleteFormSosActionPerformed

    private void btnInsertFormSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertFormSosActionPerformed
        
    }//GEN-LAST:event_btnInsertFormSosActionPerformed

    private void buttonInsertSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonInsertSosActionPerformed
        panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(true);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(false);
        textNIMSosInsert.setEditable(true);
        textNIMSosInsert.setText("");
        textNamaSosInsert.setText("");
        textKelasSosInsert.setText("");
        textNamaSosInsert.setEditable(false);
        textKelasSosInsert.setEditable(false);
        textMatSosInsert.setEditable(false);
        textIPSinsert.setEditable(false);
        textBISosInsert.setEditable(false);
        textBingSosInsert.setEditable(false);
        
    }//GEN-LAST:event_buttonInsertSosActionPerformed

    private void btnShowSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowSosActionPerformed
        showDataStudent();
    }//GEN-LAST:event_btnShowSosActionPerformed

    private void buttonUpdateSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateSosActionPerformed
         panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(false);
        panelUpdateSos.setVisible(true);
         textNamaUpdateSos.setText("");
        textKelasUpdateSos.setText("");
        textNIMSosUpdate.setText("");
        textNIMSosUpdate.setEditable(true);
        textNamaUpdateSos.setEditable(false);
        textKelasUpdateSos.setEditable(false);
        textMatUpdateSos.setEditable(false);
        textIPSUpdate.setEditable(false);
        textBIUpdateSos.setEditable(false);
        textBingUpdateSos.setEditable(false);
    }//GEN-LAST:event_buttonUpdateSosActionPerformed

    private void buttonDeleteSosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteSosActionPerformed
          panelInsert.setVisible(false);
        panelDelete.setVisible(false);
        panelUpdate.setVisible(false);
        panelInsertSos.setVisible(false);
        panelDeleteSos.setVisible(true);
        panelUpdateSos.setVisible(false);
    }//GEN-LAST:event_buttonDeleteSosActionPerformed

    private void btn_add_student1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_student1ActionPerformed
        AddStudentForm add = new AddStudentForm();
        add.setVisible(true);
    }//GEN-LAST:event_btn_add_student1ActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        if("".equals(txt_nim.getText())) JOptionPane.showMessageDialog(null, "Please insert the NIM", "Empty Field", JOptionPane.WARNING_MESSAGE);
        else{
            String nim = txt_nim.getText();
            grade_sc = new GradeSCDAO();
            rs = grade_sc.getGradeByNim(nim);
            try{
                if(rs.next()){
                    txt_name.setText(rs.getString("st_name"));
                    txt_class.setText(rs.getString("st_class"));
                    txt_mtk.setText(rs.getString("score_mtk"));
                    txt_ipa.setText(rs.getString("score_ipa"));
                    txt_indo.setText(rs.getString("score_indo"));
                    txt_eng.setText(rs.getString("score_inggris"));
                    txt_nim.setEnabled(false);
                    btn_search.setEnabled(false);
                    btn_cancel.setEnabled(true);
                    btn_delete.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(null, "Grade of Student with NIM : " + nim +" doesn't exist", "Grade not Found", JOptionPane.WARNING_MESSAGE);
                }
            }
            catch (SQLException ex) {
                Logger.getLogger(GradeRecordsGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        canceldeletion();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void txt_nimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nimKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACKSPACE) || (c == KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txt_nimKeyTyped
    
    private void canceldeletion(){
        txt_name.setText("- - -");
        txt_class.setText("- - -");
        txt_mtk.setText("- - -");
        txt_ipa.setText("- - -");
        txt_indo.setText("- - - ");
        txt_eng.setText("- - -");
        txt_nim.setText("");
        txt_nim.setEnabled(true);
        btn_search.setEnabled(true);
        btn_cancel.setEnabled(false);
        btn_delete.setEnabled(false);
    }
    
    private DefaultTableModel tabelModelData()
    {      
        String[] namaKolom = {"NIM", "Nama Siswa/Siswi", "Kelas", "Status"};
        int rows = 0;
        try{
            while (rs.next()){
                rows = rs.getRow();
            }
            rs.beforeFirst();
            dataStudent = new String[rows][namaKolom.length];
            for (int i = 0; i < rows; i++) {
                rs.next();
                for (int j = 0; j < namaKolom.length; j++) {
                    dataStudent[i][j] = rs.getString(j + 1);
                }
            }
        } catch (Exception ex){}
        return new DefaultTableModel(dataStudent, namaKolom);
    }


    private void showDataStudent() {
        try {
            stud = new StudentDAO();
            rs = stud.getbyClass(txtlog_class.getText());
            tableSiswa.setModel(tabelModelData());
            tableSiswa.setEnabled(true);
        } catch (Exception e) {
            e.getMessage();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GradeRecordsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GradeRecordsGUI().setVisible(true);    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelAwal;
    private javax.swing.JButton btnDeleteFormSos;
    private javax.swing.JButton btnInsertForm;
    private javax.swing.JButton btnInsertFormSos;
    private javax.swing.JButton btnSearchUpdate;
    private javax.swing.JButton btnSearchUpdateSOS;
    private javax.swing.JButton btnShow;
    private javax.swing.JButton btnShowSos;
    private javax.swing.JButton btnUpdateForm;
    private javax.swing.JButton btnUpdateSos;
    private javax.swing.JButton btn_add_student;
    private javax.swing.JButton btn_add_student1;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonDeleteSos;
    private javax.swing.JButton buttonInsert;
    private javax.swing.JButton buttonInsertSos;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton buttonUpdateSos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblBindo;
    private javax.swing.JLabel lblBindoD;
    private javax.swing.JLabel lblBindoDSos;
    private javax.swing.JLabel lblBindoI;
    private javax.swing.JLabel lblBindoISos;
    private javax.swing.JLabel lblBindoSos;
    private javax.swing.JLabel lblBinggris;
    private javax.swing.JLabel lblBinggrisD;
    private javax.swing.JLabel lblBinggrisD1;
    private javax.swing.JLabel lblBinggrisI;
    private javax.swing.JLabel lblBinggrisI1;
    private javax.swing.JLabel lblBinggrisSos;

    private javax.swing.JLabel lblBiologi;
    private javax.swing.JLabel lblBiologiI;
    private javax.swing.JLabel lblFisika;
    private javax.swing.JLabel lblFisikaD;
    private javax.swing.JLabel lblFisikaI;

    private javax.swing.JLabel lblFormDelete;
    private javax.swing.JLabel lblFormDeleteSos;
    private javax.swing.JLabel lblFormInsert;
    private javax.swing.JLabel lblFormInsertSos;
    private javax.swing.JLabel lblIPAD;
    private javax.swing.JLabel lblIPAI;
    private javax.swing.JLabel lblIPAu;
    private javax.swing.JLabel lblIPS;
    private javax.swing.JLabel lblIPSDSos;
    private javax.swing.JLabel lblIconNama;
    private javax.swing.JLabel lblIconPassword;
    private javax.swing.JLabel lblKelas;
    private javax.swing.JLabel lblKelasD;
    private javax.swing.JLabel lblKelasD1;
    private javax.swing.JLabel lblKelasDSos;
    private javax.swing.JLabel lblKelasI;
    private javax.swing.JLabel lblKelasI1;
    private javax.swing.JLabel lblKelasSos;
    private javax.swing.JLabel lblMat;
    private javax.swing.JLabel lblMatD;
    private javax.swing.JLabel lblMatDSos;
    private javax.swing.JLabel lblMatI;
    private javax.swing.JLabel lblMatI1;
    private javax.swing.JLabel lblMatSos;
    private javax.swing.JLabel lblNIMSos;
    private javax.swing.JLabel lblNIMsos;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblNamaD;
    private javax.swing.JLabel lblNamaDSos;
    private javax.swing.JLabel lblNamaI;
    private javax.swing.JLabel lblNamaI1;
    private javax.swing.JLabel lblNamaSos;
    private javax.swing.JLabel lblTITLEFORM;
    private javax.swing.JLabel lblTITLESOS;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUNIPS;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel panelAfterLogin;
    private javax.swing.JPanel panelButton;
    private javax.swing.JPanel panelButtonSos;
    private javax.swing.JPanel panelDelete;
    private javax.swing.JPanel panelDeleteSos;
    private javax.swing.JPanel panelFormLogin;
    private javax.swing.JPanel panelIcon;
    private javax.swing.JPanel panelIconAfterLogin;
    private javax.swing.JPanel panelInsert;
    private javax.swing.JPanel panelInsertSos;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelTable;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelUpdateSos;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton searchButtonInsert;
    private javax.swing.JButton searchInsertButton;
    private javax.swing.JTable tableSiswa;
    private javax.swing.JTextField textBISosInsert;
    private javax.swing.JTextField textBIUpdate;
    private javax.swing.JTextField textBIUpdateSos;
    private javax.swing.JTextField textBIinsert;
    private javax.swing.JTextField textBingInsert;
    private javax.swing.JTextField textBingSosInsert;
    private javax.swing.JTextField textBingUpdate;
    private javax.swing.JTextField textBingUpdateSos;
    private javax.swing.JTextField textIPAInsert;
    private javax.swing.JTextField textIPSUpdate;
    private javax.swing.JTextField textIPSinsert;
    private javax.swing.JTextField textKelasInsert;
    private javax.swing.JTextField textKelasSosInsert;
    private javax.swing.JTextField textKelasUpdate;
    private javax.swing.JTextField textKelasUpdateSos;
    private javax.swing.JTextField textMatInsert;
    private javax.swing.JTextField textMatSosInsert;
    private javax.swing.JTextField textMatUpdate;
    private javax.swing.JTextField textMatUpdateSos;
    private javax.swing.JTextField textNIMInsert;
    private javax.swing.JTextField textNIMSosInsert;
    private javax.swing.JTextField textNIMSosUpdate;
    private javax.swing.JTextField textNIMUpdate;
    private javax.swing.JTextField textNamaInsert;
    private javax.swing.JTextField textNamaSosInsert;
    private javax.swing.JTextField textNamaUpdate;
    private javax.swing.JTextField textNamaUpdateSos;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNilaiIPAUpdate;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JLabel txt_class;
    private javax.swing.JLabel txt_eng;
    private javax.swing.JLabel txt_indo;
    private javax.swing.JLabel txt_ipa;
    private javax.swing.JLabel txt_mtk;
    private javax.swing.JLabel txt_name;
    private javax.swing.JTextField txt_nim;
    private javax.swing.JLabel txtlog_class;
    private javax.swing.JLabel txtlog_name;
    // End of variables declaration//GEN-END:variables
}
