/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graderecords;

/**
 *
 * @author J8138
 */
public class UpdatedGradesData extends javax.swing.JFrame {

    /**
     * Creates new form UpdatedGradesData
     */
    public UpdatedGradesData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAwal = new javax.swing.JPanel();
        panelStudentDataSC = new javax.swing.JPanel();
        lblTITLESC = new javax.swing.JLabel();
        lblNameSC = new javax.swing.JLabel();
        txtNameSC = new javax.swing.JLabel();
        lblClassSC = new javax.swing.JLabel();
        lblNIMSC = new javax.swing.JLabel();
        txtNIMSC = new javax.swing.JLabel();
        txtClassSC = new javax.swing.JLabel();
        lblGradeStatusSC = new javax.swing.JLabel();
        txtGradeStatusSC = new javax.swing.JLabel();
        panelGradesSC = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblMScoreSC = new javax.swing.JLabel();
        txtMathSC = new javax.swing.JLabel();
        lblScienceSC = new javax.swing.JLabel();
        txtScienceSC = new javax.swing.JLabel();
        lblIndoSC = new javax.swing.JLabel();
        txtIndoSC = new javax.swing.JLabel();
        lblInggrisSC = new javax.swing.JLabel();
        txtInggrisSC = new javax.swing.JLabel();
        lblGradeSC = new javax.swing.JLabel();
        txtGradeSC = new javax.swing.JLabel();
        lblStatusSC = new javax.swing.JLabel();
        txtStatusSC = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAwal.setBackground(new java.awt.Color(194, 232, 206));
        panelAwal.setMinimumSize(new java.awt.Dimension(720, 373));
        panelAwal.setLayout(null);

        panelStudentDataSC.setBackground(new java.awt.Color(242, 238, 229));

        lblTITLESC.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTITLESC.setForeground(new java.awt.Color(0, 0, 0));
        lblTITLESC.setText("STUDENT PROFILE");

        lblNameSC.setBackground(new java.awt.Color(0, 0, 0));
        lblNameSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblNameSC.setForeground(new java.awt.Color(0, 0, 0));
        lblNameSC.setText("STUDENT'S NAME :");

        txtNameSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNameSC.setForeground(new java.awt.Color(0, 0, 0));
        txtNameSC.setText("---");

        lblClassSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblClassSC.setForeground(new java.awt.Color(0, 0, 0));
        lblClassSC.setText("CLASS :");

        lblNIMSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblNIMSC.setForeground(new java.awt.Color(0, 0, 0));
        lblNIMSC.setText("STUDENT'S NIM :");

        txtNIMSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNIMSC.setForeground(new java.awt.Color(0, 0, 0));
        txtNIMSC.setText("---");

        txtClassSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtClassSC.setForeground(new java.awt.Color(0, 0, 0));
        txtClassSC.setText("---");

        lblGradeStatusSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblGradeStatusSC.setForeground(new java.awt.Color(0, 0, 0));
        lblGradeStatusSC.setText("GRADE STATUS :");

        txtGradeStatusSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtGradeStatusSC.setForeground(new java.awt.Color(0, 0, 0));
        txtGradeStatusSC.setText("---");

        javax.swing.GroupLayout panelStudentDataSCLayout = new javax.swing.GroupLayout(panelStudentDataSC);
        panelStudentDataSC.setLayout(panelStudentDataSCLayout);
        panelStudentDataSCLayout.setHorizontalGroup(
            panelStudentDataSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                .addGroup(panelStudentDataSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNameSC))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblTITLESC))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClassSC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNIMSC))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNIMSC))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNameSC, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtClassSC))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGradeStatusSC))
                    .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtGradeStatusSC)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelStudentDataSCLayout.setVerticalGroup(
            panelStudentDataSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentDataSCLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTITLESC)
                .addGap(15, 15, 15)
                .addComponent(lblNIMSC)
                .addGap(7, 7, 7)
                .addComponent(txtNIMSC)
                .addGap(18, 18, 18)
                .addComponent(lblNameSC, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNameSC)
                .addGap(18, 18, 18)
                .addComponent(lblClassSC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassSC)
                .addGap(18, 18, 18)
                .addComponent(lblGradeStatusSC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradeStatusSC)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelAwal.add(panelStudentDataSC);
        panelStudentDataSC.setBounds(12, 12, 290, 350);

        panelGradesSC.setBackground(new java.awt.Color(242, 238, 229));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("GRADES REPORT");

        lblMScoreSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMScoreSC.setForeground(new java.awt.Color(0, 0, 0));
        lblMScoreSC.setText("Math Score :");

        txtMathSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtMathSC.setForeground(new java.awt.Color(0, 0, 0));
        txtMathSC.setText("---");

        lblScienceSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblScienceSC.setForeground(new java.awt.Color(0, 0, 0));
        lblScienceSC.setText("Science Score :");

        txtScienceSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtScienceSC.setForeground(new java.awt.Color(0, 0, 0));
        txtScienceSC.setText("---");

        lblIndoSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIndoSC.setForeground(new java.awt.Color(0, 0, 0));
        lblIndoSC.setText("Bahasa Indonesia Score :");

        txtIndoSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtIndoSC.setForeground(new java.awt.Color(0, 0, 0));
        txtIndoSC.setText("---");

        lblInggrisSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblInggrisSC.setForeground(new java.awt.Color(0, 0, 0));
        lblInggrisSC.setText("English Score :");

        txtInggrisSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtInggrisSC.setForeground(new java.awt.Color(0, 0, 0));
        txtInggrisSC.setText("---");

        lblGradeSC.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblGradeSC.setForeground(new java.awt.Color(0, 0, 0));
        lblGradeSC.setText("GRADE :");

        txtGradeSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtGradeSC.setForeground(new java.awt.Color(0, 0, 0));
        txtGradeSC.setText("---");

        lblStatusSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblStatusSC.setForeground(new java.awt.Color(0, 0, 0));
        lblStatusSC.setText("STATUS :");

        txtStatusSC.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtStatusSC.setForeground(new java.awt.Color(0, 0, 0));
        txtStatusSC.setText("---");

        javax.swing.GroupLayout panelGradesSCLayout = new javax.swing.GroupLayout(panelGradesSC);
        panelGradesSC.setLayout(panelGradesSCLayout);
        panelGradesSCLayout.setHorizontalGroup(
            panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradesSCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMScoreSC)
                        .addComponent(txtMathSC)
                        .addComponent(lblScienceSC))
                    .addGroup(panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtScienceSC)
                        .addComponent(lblIndoSC)
                        .addComponent(txtIndoSC)
                        .addComponent(lblInggrisSC)
                        .addComponent(txtInggrisSC)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGradeSC, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatusSC))
                .addGap(18, 18, 18)
                .addGroup(panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGradeSC, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatusSC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(panelGradesSCLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGradesSCLayout.setVerticalGroup(
            panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradesSCLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMScoreSC)
                    .addComponent(lblGradeSC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGradeSC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(txtMathSC)
                .addGap(18, 18, 18)
                .addGroup(panelGradesSCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblScienceSC)
                    .addComponent(lblStatusSC)
                    .addComponent(txtStatusSC))
                .addGap(18, 18, 18)
                .addComponent(txtScienceSC)
                .addGap(18, 18, 18)
                .addComponent(lblIndoSC)
                .addGap(18, 18, 18)
                .addComponent(txtIndoSC)
                .addGap(18, 18, 18)
                .addComponent(lblInggrisSC)
                .addGap(18, 18, 18)
                .addComponent(txtInggrisSC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAwal.add(panelGradesSC);
        panelGradesSC.setBounds(320, 10, 330, 350);

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        panelAwal.add(closeButton);
        closeButton.setBounds(660, 10, 50, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatedGradesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatedGradesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatedGradesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatedGradesData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdatedGradesData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClassSC;
    private javax.swing.JLabel lblGradeSC;
    private javax.swing.JLabel lblGradeStatusSC;
    private javax.swing.JLabel lblIndoSC;
    private javax.swing.JLabel lblInggrisSC;
    private javax.swing.JLabel lblMScoreSC;
    private javax.swing.JLabel lblNIMSC;
    private javax.swing.JLabel lblNameSC;
    private javax.swing.JLabel lblScienceSC;
    private javax.swing.JLabel lblStatusSC;
    private javax.swing.JLabel lblTITLESC;
    private javax.swing.JPanel panelAwal;
    private javax.swing.JPanel panelGradesSC;
    private javax.swing.JPanel panelStudentDataSC;
    public javax.swing.JLabel txtClassSC;
    private javax.swing.JLabel txtGradeSC;
    public javax.swing.JLabel txtGradeStatusSC;
    private javax.swing.JLabel txtIndoSC;
    private javax.swing.JLabel txtInggrisSC;
    private javax.swing.JLabel txtMathSC;
    public javax.swing.JLabel txtNIMSC;
    public javax.swing.JLabel txtNameSC;
    private javax.swing.JLabel txtScienceSC;
    private javax.swing.JLabel txtStatusSC;
    // End of variables declaration//GEN-END:variables
}
