/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graderecords;

/**
 *
 * @author J8138
 */
public class UpgradeGradesDataSO extends javax.swing.JFrame {

    /**
     * Creates new form UpdatedGradesData
     */
    public UpgradeGradesDataSO() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAwal = new javax.swing.JPanel();
        panelStudentDataSO = new javax.swing.JPanel();
        lblTITLESO = new javax.swing.JLabel();
        lblNameSO = new javax.swing.JLabel();
        txtNamaSO = new javax.swing.JLabel();
        lblClassSO = new javax.swing.JLabel();
        lblNIMSO = new javax.swing.JLabel();
        txtNIMSO = new javax.swing.JLabel();
        txtClassSO = new javax.swing.JLabel();
        lblGradeStatusSO = new javax.swing.JLabel();
        txtGradeStatusSO = new javax.swing.JLabel();
        panelGradesSO = new javax.swing.JPanel();
        lblTITLEGRADESSO = new javax.swing.JLabel();
        lblMScoreSO = new javax.swing.JLabel();
        txtMathSO = new javax.swing.JLabel();
        lblSocialSO = new javax.swing.JLabel();
        txtSocialSO = new javax.swing.JLabel();
        lblIndoSO = new javax.swing.JLabel();
        txtIndoSO = new javax.swing.JLabel();
        lblInggrisSO = new javax.swing.JLabel();
        txtInggrisSO = new javax.swing.JLabel();
        lblGradeSO = new javax.swing.JLabel();
        txtGradeSO = new javax.swing.JLabel();
        lblStatusSO = new javax.swing.JLabel();
        txtStatusSO = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAwal.setBackground(new java.awt.Color(194, 232, 206));
        panelAwal.setMinimumSize(new java.awt.Dimension(720, 373));
        panelAwal.setLayout(null);

        panelStudentDataSO.setBackground(new java.awt.Color(242, 238, 229));

        lblTITLESO.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTITLESO.setForeground(new java.awt.Color(0, 0, 0));
        lblTITLESO.setText("STUDENT PROFILE");

        lblNameSO.setBackground(new java.awt.Color(0, 0, 0));
        lblNameSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblNameSO.setForeground(new java.awt.Color(0, 0, 0));
        lblNameSO.setText("STUDENT'S NAME :");

        txtNamaSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNamaSO.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaSO.setText("---");

        lblClassSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblClassSO.setForeground(new java.awt.Color(0, 0, 0));
        lblClassSO.setText("CLASS :");

        lblNIMSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblNIMSO.setForeground(new java.awt.Color(0, 0, 0));
        lblNIMSO.setText("STUDENT'S NIM :");

        txtNIMSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtNIMSO.setForeground(new java.awt.Color(0, 0, 0));
        txtNIMSO.setText("---");

        txtClassSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtClassSO.setForeground(new java.awt.Color(0, 0, 0));
        txtClassSO.setText("---");

        lblGradeStatusSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblGradeStatusSO.setForeground(new java.awt.Color(0, 0, 0));
        lblGradeStatusSO.setText("GRADE STATUS :");

        txtGradeStatusSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtGradeStatusSO.setForeground(new java.awt.Color(0, 0, 0));
        txtGradeStatusSO.setText("---");

        javax.swing.GroupLayout panelStudentDataSOLayout = new javax.swing.GroupLayout(panelStudentDataSO);
        panelStudentDataSO.setLayout(panelStudentDataSOLayout);
        panelStudentDataSOLayout.setHorizontalGroup(
            panelStudentDataSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                .addGroup(panelStudentDataSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNameSO))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblTITLESO))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblClassSO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNIMSO))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNIMSO))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtNamaSO, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtClassSO))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblGradeStatusSO))
                    .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtGradeStatusSO)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        panelStudentDataSOLayout.setVerticalGroup(
            panelStudentDataSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStudentDataSOLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTITLESO)
                .addGap(15, 15, 15)
                .addComponent(lblNIMSO)
                .addGap(7, 7, 7)
                .addComponent(txtNIMSO)
                .addGap(18, 18, 18)
                .addComponent(lblNameSO, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNamaSO)
                .addGap(18, 18, 18)
                .addComponent(lblClassSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtClassSO)
                .addGap(18, 18, 18)
                .addComponent(lblGradeStatusSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGradeStatusSO)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        panelAwal.add(panelStudentDataSO);
        panelStudentDataSO.setBounds(12, 12, 290, 350);

        panelGradesSO.setBackground(new java.awt.Color(242, 238, 229));

        lblTITLEGRADESSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        lblTITLEGRADESSO.setForeground(new java.awt.Color(0, 0, 0));
        lblTITLEGRADESSO.setText("GRADES REPORT");

        lblMScoreSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblMScoreSO.setForeground(new java.awt.Color(0, 0, 0));
        lblMScoreSO.setText("Math Score :");

        txtMathSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtMathSO.setForeground(new java.awt.Color(0, 0, 0));
        txtMathSO.setText("---");

        lblSocialSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblSocialSO.setForeground(new java.awt.Color(0, 0, 0));
        lblSocialSO.setText("Social Score :");

        txtSocialSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtSocialSO.setForeground(new java.awt.Color(0, 0, 0));
        txtSocialSO.setText("---");

        lblIndoSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblIndoSO.setForeground(new java.awt.Color(0, 0, 0));
        lblIndoSO.setText("Bahasa Indonesia Score :");

        txtIndoSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtIndoSO.setForeground(new java.awt.Color(0, 0, 0));
        txtIndoSO.setText("---");

        lblInggrisSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        lblInggrisSO.setForeground(new java.awt.Color(0, 0, 0));
        lblInggrisSO.setText("English Score :");

        txtInggrisSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        txtInggrisSO.setForeground(new java.awt.Color(0, 0, 0));
        txtInggrisSO.setText("---");

        lblGradeSO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblGradeSO.setForeground(new java.awt.Color(0, 0, 0));
        lblGradeSO.setText("GRADE :");

        txtGradeSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtGradeSO.setForeground(new java.awt.Color(0, 0, 0));
        txtGradeSO.setText("---");

        lblStatusSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblStatusSO.setForeground(new java.awt.Color(0, 0, 0));
        lblStatusSO.setText("STATUS :");

        txtStatusSO.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        txtStatusSO.setForeground(new java.awt.Color(0, 0, 0));
        txtStatusSO.setText("---");

        javax.swing.GroupLayout panelGradesSOLayout = new javax.swing.GroupLayout(panelGradesSO);
        panelGradesSO.setLayout(panelGradesSOLayout);
        panelGradesSOLayout.setHorizontalGroup(
            panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradesSOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradesSOLayout.createSequentialGroup()
                        .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMScoreSO)
                            .addComponent(txtMathSO)
                            .addComponent(lblSocialSO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE))
                    .addGroup(panelGradesSOLayout.createSequentialGroup()
                        .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSocialSO)
                            .addComponent(lblIndoSO)
                            .addComponent(txtIndoSO)
                            .addComponent(lblInggrisSO)
                            .addComponent(txtInggrisSO))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)))
                .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradesSOLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(txtGradeSO))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradesSOLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtStatusSO)))
                .addContainerGap())
            .addGroup(panelGradesSOLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTITLEGRADESSO)
                    .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblStatusSO)
                        .addComponent(lblGradeSO, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGradesSOLayout.setVerticalGroup(
            panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradesSOLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTITLEGRADESSO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMScoreSO)
                    .addComponent(lblGradeSO, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGradeSO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addComponent(txtMathSO)
                .addGap(18, 18, 18)
                .addGroup(panelGradesSOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSocialSO)
                    .addComponent(lblStatusSO)
                    .addComponent(txtStatusSO))
                .addGap(18, 18, 18)
                .addComponent(txtSocialSO)
                .addGap(18, 18, 18)
                .addComponent(lblIndoSO)
                .addGap(18, 18, 18)
                .addComponent(txtIndoSO)
                .addGap(18, 18, 18)
                .addComponent(lblInggrisSO)
                .addGap(18, 18, 18)
                .addComponent(txtInggrisSO)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAwal.add(panelGradesSO);
        panelGradesSO.setBounds(320, 10, 330, 350);

        closeButton.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        closeButton.setText("X");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        panelAwal.add(closeButton);
        closeButton.setBounds(660, 10, 50, 26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelAwal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpgradeGradesDataSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpgradeGradesDataSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpgradeGradesDataSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpgradeGradesDataSO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpgradeGradesDataSO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel lblClassSO;
    private javax.swing.JLabel lblGradeSO;
    private javax.swing.JLabel lblGradeStatusSO;
    private javax.swing.JLabel lblIndoSO;
    private javax.swing.JLabel lblInggrisSO;
    private javax.swing.JLabel lblMScoreSO;
    private javax.swing.JLabel lblNIMSO;
    private javax.swing.JLabel lblNameSO;
    private javax.swing.JLabel lblSocialSO;
    private javax.swing.JLabel lblStatusSO;
    private javax.swing.JLabel lblTITLEGRADESSO;
    private javax.swing.JLabel lblTITLESO;
    private javax.swing.JPanel panelAwal;
    public javax.swing.JPanel panelGradesSO;
    public javax.swing.JPanel panelStudentDataSO;
    public javax.swing.JLabel txtClassSO;
    private javax.swing.JLabel txtGradeSO;
    public javax.swing.JLabel txtGradeStatusSO;
    private javax.swing.JLabel txtIndoSO;
    private javax.swing.JLabel txtInggrisSO;
    private javax.swing.JLabel txtMathSO;
    public javax.swing.JLabel txtNIMSO;
    public javax.swing.JLabel txtNamaSO;
    private javax.swing.JLabel txtSocialSO;
    private javax.swing.JLabel txtStatusSO;
    // End of variables declaration//GEN-END:variables
}
